//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetworkClient.HallService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", ConfigurationName="HallService.IHallService")]
    public interface IHallService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/removeHallReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/removeHallRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EntertainmentNetworkClient.HallService.removeHallResponse removeHall(EntertainmentNetworkClient.HallService.removeHallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/removeHallReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/removeHallRes" +
            "ponse")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.removeHallResponse> removeHallAsync(EntertainmentNetworkClient.HallService.removeHallRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/findHallByIdR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/findHallByIdR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetworkClient.HallService.findHallByIdResponse findHallById(EntertainmentNetworkClient.HallService.findHallByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/findHallByIdR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/findHallByIdR" +
            "esponse")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.findHallByIdResponse> findHallByIdAsync(EntertainmentNetworkClient.HallService.findHallByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/mergeHallRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/mergeHallResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetworkClient.HallService.mergeHallResponse mergeHall(EntertainmentNetworkClient.HallService.mergeHallRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/mergeHallRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/mergeHallResp" +
            "onse")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.mergeHallResponse> mergeHallAsync(EntertainmentNetworkClient.HallService.mergeHallRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/getHallsReque" +
            "st", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/getHallsRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetworkClient.HallService.getHallsResponse getHalls(EntertainmentNetworkClient.HallService.getHallsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/getHallsReque" +
            "st", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/getHallsRespo" +
            "nse")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.getHallsResponse> getHallsAsync(EntertainmentNetworkClient.HallService.getHallsRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/addHallReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/addHallRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        EntertainmentNetworkClient.HallService.addHallResponse addHall(EntertainmentNetworkClient.HallService.addHallRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/addHallReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/addHallRespon" +
            "se")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.addHallResponse> addHallAsync(EntertainmentNetworkClient.HallService.addHallRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeHall", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeHallRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeHallRequest() {
        }
        
        public removeHallRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeHallResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeHallResponse {
        
        public removeHallResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class hall : baseModel {
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        private string halNameField;
        
        private decimal halSitscountField;
        
        private bool halSitscountFieldSpecified;
        
        private sit[] sitsField;
        
        private decimal cinemaIdField;
        
        private bool cinemaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string halName {
            get {
                return this.halNameField;
            }
            set {
                this.halNameField = value;
                this.RaisePropertyChanged("halName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal halSitscount {
            get {
                return this.halSitscountField;
            }
            set {
                this.halSitscountField = value;
                this.RaisePropertyChanged("halSitscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halSitscountSpecified {
            get {
                return this.halSitscountFieldSpecified;
            }
            set {
                this.halSitscountFieldSpecified = value;
                this.RaisePropertyChanged("halSitscountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sits", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public sit[] sits {
            get {
                return this.sitsField;
            }
            set {
                this.sitsField = value;
                this.RaisePropertyChanged("sits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal cinemaId {
            get {
                return this.cinemaIdField;
            }
            set {
                this.cinemaIdField = value;
                this.RaisePropertyChanged("cinemaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinemaIdSpecified {
            get {
                return this.cinemaIdFieldSpecified;
            }
            set {
                this.cinemaIdFieldSpecified = value;
                this.RaisePropertyChanged("cinemaIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class sit : baseModel {
        
        private decimal sitIdField;
        
        private bool sitIdFieldSpecified;
        
        private decimal sitNumField;
        
        private bool sitNumFieldSpecified;
        
        private decimal sitRowField;
        
        private bool sitRowFieldSpecified;
        
        private decimal sitFloorField;
        
        private bool sitFloorFieldSpecified;
        
        private decimal sitTypeField;
        
        private bool sitTypeFieldSpecified;
        
        private decimal cinemaIdField;
        
        private bool cinemaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal sitId {
            get {
                return this.sitIdField;
            }
            set {
                this.sitIdField = value;
                this.RaisePropertyChanged("sitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitIdSpecified {
            get {
                return this.sitIdFieldSpecified;
            }
            set {
                this.sitIdFieldSpecified = value;
                this.RaisePropertyChanged("sitIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal sitNum {
            get {
                return this.sitNumField;
            }
            set {
                this.sitNumField = value;
                this.RaisePropertyChanged("sitNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitNumSpecified {
            get {
                return this.sitNumFieldSpecified;
            }
            set {
                this.sitNumFieldSpecified = value;
                this.RaisePropertyChanged("sitNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal sitRow {
            get {
                return this.sitRowField;
            }
            set {
                this.sitRowField = value;
                this.RaisePropertyChanged("sitRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitRowSpecified {
            get {
                return this.sitRowFieldSpecified;
            }
            set {
                this.sitRowFieldSpecified = value;
                this.RaisePropertyChanged("sitRowSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal sitFloor {
            get {
                return this.sitFloorField;
            }
            set {
                this.sitFloorField = value;
                this.RaisePropertyChanged("sitFloor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitFloorSpecified {
            get {
                return this.sitFloorFieldSpecified;
            }
            set {
                this.sitFloorFieldSpecified = value;
                this.RaisePropertyChanged("sitFloorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal sitType {
            get {
                return this.sitTypeField;
            }
            set {
                this.sitTypeField = value;
                this.RaisePropertyChanged("sitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitTypeSpecified {
            get {
                return this.sitTypeFieldSpecified;
            }
            set {
                this.sitTypeFieldSpecified = value;
                this.RaisePropertyChanged("sitTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal cinemaId {
            get {
                return this.cinemaIdField;
            }
            set {
                this.cinemaIdField = value;
                this.RaisePropertyChanged("cinemaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinemaIdSpecified {
            get {
                return this.cinemaIdFieldSpecified;
            }
            set {
                this.cinemaIdFieldSpecified = value;
                this.RaisePropertyChanged("cinemaIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hall))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addHallRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeHallRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeHallRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class addHallRequest : baseDto {
        
        private decimal cinIdField;
        
        private bool cinIdFieldSpecified;
        
        private string halNameField;
        
        private decimal halSitscountField;
        
        private bool halSitscountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal cinId {
            get {
                return this.cinIdField;
            }
            set {
                this.cinIdField = value;
                this.RaisePropertyChanged("cinId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinIdSpecified {
            get {
                return this.cinIdFieldSpecified;
            }
            set {
                this.cinIdFieldSpecified = value;
                this.RaisePropertyChanged("cinIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string halName {
            get {
                return this.halNameField;
            }
            set {
                this.halNameField = value;
                this.RaisePropertyChanged("halName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal halSitscount {
            get {
                return this.halSitscountField;
            }
            set {
                this.halSitscountField = value;
                this.RaisePropertyChanged("halSitscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halSitscountSpecified {
            get {
                return this.halSitscountFieldSpecified;
            }
            set {
                this.halSitscountFieldSpecified = value;
                this.RaisePropertyChanged("halSitscountSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class mergeHallRequest : addHallRequest {
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findHallById", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findHallByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findHallByIdRequest() {
        }
        
        public findHallByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findHallByIdResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findHallByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.HallService.hall @return;
        
        public findHallByIdResponse() {
        }
        
        public findHallByIdResponse(EntertainmentNetworkClient.HallService.hall @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeHall", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeHallRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.HallService.mergeHallRequest arg0;
        
        public mergeHallRequest1() {
        }
        
        public mergeHallRequest1(EntertainmentNetworkClient.HallService.mergeHallRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeHallResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeHallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.HallService.hall @return;
        
        public mergeHallResponse() {
        }
        
        public mergeHallResponse(EntertainmentNetworkClient.HallService.hall @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHalls", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getHallsRequest {
        
        public getHallsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHallsResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getHallsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.HallService.hall[] @return;
        
        public getHallsResponse() {
        }
        
        public getHallsResponse(EntertainmentNetworkClient.HallService.hall[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addHall", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addHallRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.HallService.addHallRequest arg0;
        
        public addHallRequest1() {
        }
        
        public addHallRequest1(EntertainmentNetworkClient.HallService.addHallRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addHallResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addHallResponse {
        
        public addHallResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHallServiceChannel : EntertainmentNetworkClient.HallService.IHallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HallServiceClient : System.ServiceModel.ClientBase<EntertainmentNetworkClient.HallService.IHallService>, EntertainmentNetworkClient.HallService.IHallService {
        
        public HallServiceClient() {
        }
        
        public HallServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HallServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HallServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HallServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.HallService.removeHallResponse EntertainmentNetworkClient.HallService.IHallService.removeHall(EntertainmentNetworkClient.HallService.removeHallRequest request) {
            return base.Channel.removeHall(request);
        }
        
        public void removeHall(decimal arg0) {
            EntertainmentNetworkClient.HallService.removeHallRequest inValue = new EntertainmentNetworkClient.HallService.removeHallRequest();
            inValue.arg0 = arg0;
            EntertainmentNetworkClient.HallService.removeHallResponse retVal = ((EntertainmentNetworkClient.HallService.IHallService)(this)).removeHall(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.removeHallResponse> EntertainmentNetworkClient.HallService.IHallService.removeHallAsync(EntertainmentNetworkClient.HallService.removeHallRequest request) {
            return base.Channel.removeHallAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.removeHallResponse> removeHallAsync(decimal arg0) {
            EntertainmentNetworkClient.HallService.removeHallRequest inValue = new EntertainmentNetworkClient.HallService.removeHallRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetworkClient.HallService.IHallService)(this)).removeHallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.HallService.findHallByIdResponse EntertainmentNetworkClient.HallService.IHallService.findHallById(EntertainmentNetworkClient.HallService.findHallByIdRequest request) {
            return base.Channel.findHallById(request);
        }
        
        public EntertainmentNetworkClient.HallService.hall findHallById(decimal arg0) {
            EntertainmentNetworkClient.HallService.findHallByIdRequest inValue = new EntertainmentNetworkClient.HallService.findHallByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetworkClient.HallService.findHallByIdResponse retVal = ((EntertainmentNetworkClient.HallService.IHallService)(this)).findHallById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.findHallByIdResponse> EntertainmentNetworkClient.HallService.IHallService.findHallByIdAsync(EntertainmentNetworkClient.HallService.findHallByIdRequest request) {
            return base.Channel.findHallByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.findHallByIdResponse> findHallByIdAsync(decimal arg0) {
            EntertainmentNetworkClient.HallService.findHallByIdRequest inValue = new EntertainmentNetworkClient.HallService.findHallByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetworkClient.HallService.IHallService)(this)).findHallByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.HallService.mergeHallResponse EntertainmentNetworkClient.HallService.IHallService.mergeHall(EntertainmentNetworkClient.HallService.mergeHallRequest1 request) {
            return base.Channel.mergeHall(request);
        }
        
        public EntertainmentNetworkClient.HallService.hall mergeHall(EntertainmentNetworkClient.HallService.mergeHallRequest arg0) {
            EntertainmentNetworkClient.HallService.mergeHallRequest1 inValue = new EntertainmentNetworkClient.HallService.mergeHallRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetworkClient.HallService.mergeHallResponse retVal = ((EntertainmentNetworkClient.HallService.IHallService)(this)).mergeHall(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.mergeHallResponse> EntertainmentNetworkClient.HallService.IHallService.mergeHallAsync(EntertainmentNetworkClient.HallService.mergeHallRequest1 request) {
            return base.Channel.mergeHallAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.mergeHallResponse> mergeHallAsync(EntertainmentNetworkClient.HallService.mergeHallRequest arg0) {
            EntertainmentNetworkClient.HallService.mergeHallRequest1 inValue = new EntertainmentNetworkClient.HallService.mergeHallRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetworkClient.HallService.IHallService)(this)).mergeHallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.HallService.getHallsResponse EntertainmentNetworkClient.HallService.IHallService.getHalls(EntertainmentNetworkClient.HallService.getHallsRequest request) {
            return base.Channel.getHalls(request);
        }
        
        public EntertainmentNetworkClient.HallService.hall[] getHalls() {
            EntertainmentNetworkClient.HallService.getHallsRequest inValue = new EntertainmentNetworkClient.HallService.getHallsRequest();
            EntertainmentNetworkClient.HallService.getHallsResponse retVal = ((EntertainmentNetworkClient.HallService.IHallService)(this)).getHalls(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.getHallsResponse> EntertainmentNetworkClient.HallService.IHallService.getHallsAsync(EntertainmentNetworkClient.HallService.getHallsRequest request) {
            return base.Channel.getHallsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.getHallsResponse> getHallsAsync() {
            EntertainmentNetworkClient.HallService.getHallsRequest inValue = new EntertainmentNetworkClient.HallService.getHallsRequest();
            return ((EntertainmentNetworkClient.HallService.IHallService)(this)).getHallsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.HallService.addHallResponse EntertainmentNetworkClient.HallService.IHallService.addHall(EntertainmentNetworkClient.HallService.addHallRequest1 request) {
            return base.Channel.addHall(request);
        }
        
        public void addHall(EntertainmentNetworkClient.HallService.addHallRequest arg0) {
            EntertainmentNetworkClient.HallService.addHallRequest1 inValue = new EntertainmentNetworkClient.HallService.addHallRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetworkClient.HallService.addHallResponse retVal = ((EntertainmentNetworkClient.HallService.IHallService)(this)).addHall(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.addHallResponse> EntertainmentNetworkClient.HallService.IHallService.addHallAsync(EntertainmentNetworkClient.HallService.addHallRequest1 request) {
            return base.Channel.addHallAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.HallService.addHallResponse> addHallAsync(EntertainmentNetworkClient.HallService.addHallRequest arg0) {
            EntertainmentNetworkClient.HallService.addHallRequest1 inValue = new EntertainmentNetworkClient.HallService.addHallRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetworkClient.HallService.IHallService)(this)).addHallAsync(inValue);
        }
    }
}
