//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.FloorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", ConfigurationName="FloorService.IFloorService")]
    public interface IFloorService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/getFloorsReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/getFloorsRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.FloorService.getFloorsResponse getFloors(EntertainmentNetwork.DAL.FloorService.getFloorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/getFloorsReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/getFloorsRes" +
            "ponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.getFloorsResponse> getFloorsAsync(EntertainmentNetwork.DAL.FloorService.getFloorsRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/addFloorRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/addFloorResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        EntertainmentNetwork.DAL.FloorService.addFloorResponse addFloor(EntertainmentNetwork.DAL.FloorService.addFloorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/addFloorRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/addFloorResp" +
            "onse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.addFloorResponse> addFloorAsync(EntertainmentNetwork.DAL.FloorService.addFloorRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/findFloorByI" +
            "dRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/findFloorByI" +
            "dResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.FloorService.findFloorByIdResponse findFloorById(EntertainmentNetwork.DAL.FloorService.findFloorByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/findFloorByI" +
            "dRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/findFloorByI" +
            "dResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.findFloorByIdResponse> findFloorByIdAsync(EntertainmentNetwork.DAL.FloorService.findFloorByIdRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/removeFloorR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/removeFloorR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        EntertainmentNetwork.DAL.FloorService.removeFloorResponse removeFloor(EntertainmentNetwork.DAL.FloorService.removeFloorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/removeFloorR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/removeFloorR" +
            "esponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.removeFloorResponse> removeFloorAsync(EntertainmentNetwork.DAL.FloorService.removeFloorRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/mergeFloorRe" +
            "quest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/mergeFloorRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.FloorService.mergeFloorResponse mergeFloor(EntertainmentNetwork.DAL.FloorService.mergeFloorRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/mergeFloorRe" +
            "quest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IFloorService/mergeFloorRe" +
            "sponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.mergeFloorResponse> mergeFloorAsync(EntertainmentNetwork.DAL.FloorService.mergeFloorRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class floor : baseModel {
        
        private decimal flrIdField;
        
        private bool flrIdFieldSpecified;
        
        private string flrNameField;
        
        private decimal hallIdField;
        
        private bool hallIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal flrId {
            get {
                return this.flrIdField;
            }
            set {
                this.flrIdField = value;
                this.RaisePropertyChanged("flrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flrIdSpecified {
            get {
                return this.flrIdFieldSpecified;
            }
            set {
                this.flrIdFieldSpecified = value;
                this.RaisePropertyChanged("flrIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string flrName {
            get {
                return this.flrNameField;
            }
            set {
                this.flrNameField = value;
                this.RaisePropertyChanged("flrName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal hallId {
            get {
                return this.hallIdField;
            }
            set {
                this.hallIdField = value;
                this.RaisePropertyChanged("hallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hallIdSpecified {
            get {
                return this.hallIdFieldSpecified;
            }
            set {
                this.hallIdFieldSpecified = value;
                this.RaisePropertyChanged("hallIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(floor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addFloorRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeFloorRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeFloorRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class addFloorRequest : baseDto {
        
        private string flrNameField;
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string flrName {
            get {
                return this.flrNameField;
            }
            set {
                this.flrNameField = value;
                this.RaisePropertyChanged("flrName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class mergeFloorRequest : addFloorRequest {
        
        private decimal flrIdField;
        
        private bool flrIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal flrId {
            get {
                return this.flrIdField;
            }
            set {
                this.flrIdField = value;
                this.RaisePropertyChanged("flrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flrIdSpecified {
            get {
                return this.flrIdFieldSpecified;
            }
            set {
                this.flrIdFieldSpecified = value;
                this.RaisePropertyChanged("flrIdSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFloors", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getFloorsRequest {
        
        public getFloorsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFloorsResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getFloorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.FloorService.floor[] @return;
        
        public getFloorsResponse() {
        }
        
        public getFloorsResponse(EntertainmentNetwork.DAL.FloorService.floor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addFloor", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addFloorRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.FloorService.addFloorRequest arg0;
        
        public addFloorRequest1() {
        }
        
        public addFloorRequest1(EntertainmentNetwork.DAL.FloorService.addFloorRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addFloorResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addFloorResponse {
        
        public addFloorResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFloorById", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findFloorByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findFloorByIdRequest() {
        }
        
        public findFloorByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findFloorByIdResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findFloorByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.FloorService.floor @return;
        
        public findFloorByIdResponse() {
        }
        
        public findFloorByIdResponse(EntertainmentNetwork.DAL.FloorService.floor @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeFloor", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeFloorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeFloorRequest() {
        }
        
        public removeFloorRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeFloorResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeFloorResponse {
        
        public removeFloorResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeFloor", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeFloorRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.FloorService.mergeFloorRequest arg0;
        
        public mergeFloorRequest1() {
        }
        
        public mergeFloorRequest1(EntertainmentNetwork.DAL.FloorService.mergeFloorRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeFloorResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeFloorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.FloorService.floor @return;
        
        public mergeFloorResponse() {
        }
        
        public mergeFloorResponse(EntertainmentNetwork.DAL.FloorService.floor @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFloorServiceChannel : EntertainmentNetwork.DAL.FloorService.IFloorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FloorServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.FloorService.IFloorService>, EntertainmentNetwork.DAL.FloorService.IFloorService {
        
        public FloorServiceClient() {
        }
        
        public FloorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FloorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FloorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FloorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.FloorService.getFloorsResponse EntertainmentNetwork.DAL.FloorService.IFloorService.getFloors(EntertainmentNetwork.DAL.FloorService.getFloorsRequest request) {
            return base.Channel.getFloors(request);
        }
        
        public EntertainmentNetwork.DAL.FloorService.floor[] getFloors() {
            EntertainmentNetwork.DAL.FloorService.getFloorsRequest inValue = new EntertainmentNetwork.DAL.FloorService.getFloorsRequest();
            EntertainmentNetwork.DAL.FloorService.getFloorsResponse retVal = ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).getFloors(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.getFloorsResponse> EntertainmentNetwork.DAL.FloorService.IFloorService.getFloorsAsync(EntertainmentNetwork.DAL.FloorService.getFloorsRequest request) {
            return base.Channel.getFloorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.getFloorsResponse> getFloorsAsync() {
            EntertainmentNetwork.DAL.FloorService.getFloorsRequest inValue = new EntertainmentNetwork.DAL.FloorService.getFloorsRequest();
            return ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).getFloorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.FloorService.addFloorResponse EntertainmentNetwork.DAL.FloorService.IFloorService.addFloor(EntertainmentNetwork.DAL.FloorService.addFloorRequest1 request) {
            return base.Channel.addFloor(request);
        }
        
        public void addFloor(EntertainmentNetwork.DAL.FloorService.addFloorRequest arg0) {
            EntertainmentNetwork.DAL.FloorService.addFloorRequest1 inValue = new EntertainmentNetwork.DAL.FloorService.addFloorRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.FloorService.addFloorResponse retVal = ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).addFloor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.addFloorResponse> EntertainmentNetwork.DAL.FloorService.IFloorService.addFloorAsync(EntertainmentNetwork.DAL.FloorService.addFloorRequest1 request) {
            return base.Channel.addFloorAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.addFloorResponse> addFloorAsync(EntertainmentNetwork.DAL.FloorService.addFloorRequest arg0) {
            EntertainmentNetwork.DAL.FloorService.addFloorRequest1 inValue = new EntertainmentNetwork.DAL.FloorService.addFloorRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).addFloorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.FloorService.findFloorByIdResponse EntertainmentNetwork.DAL.FloorService.IFloorService.findFloorById(EntertainmentNetwork.DAL.FloorService.findFloorByIdRequest request) {
            return base.Channel.findFloorById(request);
        }
        
        public EntertainmentNetwork.DAL.FloorService.floor findFloorById(decimal arg0) {
            EntertainmentNetwork.DAL.FloorService.findFloorByIdRequest inValue = new EntertainmentNetwork.DAL.FloorService.findFloorByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.FloorService.findFloorByIdResponse retVal = ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).findFloorById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.findFloorByIdResponse> EntertainmentNetwork.DAL.FloorService.IFloorService.findFloorByIdAsync(EntertainmentNetwork.DAL.FloorService.findFloorByIdRequest request) {
            return base.Channel.findFloorByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.findFloorByIdResponse> findFloorByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.FloorService.findFloorByIdRequest inValue = new EntertainmentNetwork.DAL.FloorService.findFloorByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).findFloorByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.FloorService.removeFloorResponse EntertainmentNetwork.DAL.FloorService.IFloorService.removeFloor(EntertainmentNetwork.DAL.FloorService.removeFloorRequest request) {
            return base.Channel.removeFloor(request);
        }
        
        public void removeFloor(decimal arg0) {
            EntertainmentNetwork.DAL.FloorService.removeFloorRequest inValue = new EntertainmentNetwork.DAL.FloorService.removeFloorRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.FloorService.removeFloorResponse retVal = ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).removeFloor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.removeFloorResponse> EntertainmentNetwork.DAL.FloorService.IFloorService.removeFloorAsync(EntertainmentNetwork.DAL.FloorService.removeFloorRequest request) {
            return base.Channel.removeFloorAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.removeFloorResponse> removeFloorAsync(decimal arg0) {
            EntertainmentNetwork.DAL.FloorService.removeFloorRequest inValue = new EntertainmentNetwork.DAL.FloorService.removeFloorRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).removeFloorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.FloorService.mergeFloorResponse EntertainmentNetwork.DAL.FloorService.IFloorService.mergeFloor(EntertainmentNetwork.DAL.FloorService.mergeFloorRequest1 request) {
            return base.Channel.mergeFloor(request);
        }
        
        public EntertainmentNetwork.DAL.FloorService.floor mergeFloor(EntertainmentNetwork.DAL.FloorService.mergeFloorRequest arg0) {
            EntertainmentNetwork.DAL.FloorService.mergeFloorRequest1 inValue = new EntertainmentNetwork.DAL.FloorService.mergeFloorRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.FloorService.mergeFloorResponse retVal = ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).mergeFloor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.mergeFloorResponse> EntertainmentNetwork.DAL.FloorService.IFloorService.mergeFloorAsync(EntertainmentNetwork.DAL.FloorService.mergeFloorRequest1 request) {
            return base.Channel.mergeFloorAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.FloorService.mergeFloorResponse> mergeFloorAsync(EntertainmentNetwork.DAL.FloorService.mergeFloorRequest arg0) {
            EntertainmentNetwork.DAL.FloorService.mergeFloorRequest1 inValue = new EntertainmentNetwork.DAL.FloorService.mergeFloorRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.FloorService.IFloorService)(this)).mergeFloorAsync(inValue);
        }
    }
}
