//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.CityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", ConfigurationName="CityService.ICityService")]
    public interface ICityService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/findByNameReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/findByNameRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CityService.findByNameResponse findByName(EntertainmentNetwork.DAL.CityService.findByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/findByNameReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/findByNameRes" +
            "ponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.findByNameResponse> findByNameAsync(EntertainmentNetwork.DAL.CityService.findByNameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/findCityByIdR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/findCityByIdR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CityService.findCityByIdResponse findCityById(EntertainmentNetwork.DAL.CityService.findCityByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/findCityByIdR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/findCityByIdR" +
            "esponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.findCityByIdResponse> findCityByIdAsync(EntertainmentNetwork.DAL.CityService.findCityByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/mergeCityRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/mergeCityResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CityService.mergeCityResponse mergeCity(EntertainmentNetwork.DAL.CityService.mergeCityRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/mergeCityRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/mergeCityResp" +
            "onse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.mergeCityResponse> mergeCityAsync(EntertainmentNetwork.DAL.CityService.mergeCityRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/getCitiesRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/getCitiesResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CityService.getCitiesResponse getCities(EntertainmentNetwork.DAL.CityService.getCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/getCitiesRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/getCitiesResp" +
            "onse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.getCitiesResponse> getCitiesAsync(EntertainmentNetwork.DAL.CityService.getCitiesRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/removeCityReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/removeCityRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        EntertainmentNetwork.DAL.CityService.removeCityResponse removeCity(EntertainmentNetwork.DAL.CityService.removeCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/removeCityReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/removeCityRes" +
            "ponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.removeCityResponse> removeCityAsync(EntertainmentNetwork.DAL.CityService.removeCityRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/addCityReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/addCityRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        EntertainmentNetwork.DAL.CityService.addCityResponse addCity(EntertainmentNetwork.DAL.CityService.addCityRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/addCityReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICityService/addCityRespon" +
            "se")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.addCityResponse> addCityAsync(EntertainmentNetwork.DAL.CityService.addCityRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class city : baseModel {
        
        private decimal citIdField;
        
        private bool citIdFieldSpecified;
        
        private string citNameField;
        
        private string citCountryField;
        
        private cinema[] cinemasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal citId {
            get {
                return this.citIdField;
            }
            set {
                this.citIdField = value;
                this.RaisePropertyChanged("citId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool citIdSpecified {
            get {
                return this.citIdFieldSpecified;
            }
            set {
                this.citIdFieldSpecified = value;
                this.RaisePropertyChanged("citIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string citName {
            get {
                return this.citNameField;
            }
            set {
                this.citNameField = value;
                this.RaisePropertyChanged("citName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string citCountry {
            get {
                return this.citCountryField;
            }
            set {
                this.citCountryField = value;
                this.RaisePropertyChanged("citCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cinemas", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public cinema[] cinemas {
            get {
                return this.cinemasField;
            }
            set {
                this.cinemasField = value;
                this.RaisePropertyChanged("cinemas");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class cinema : baseModel {
        
        private decimal cinIdField;
        
        private bool cinIdFieldSpecified;
        
        private string cinNameField;
        
        private byte[] cinIconField;
        
        private string cinAddressField;
        
        private hall[] hallsField;
        
        private decimal cityIdField;
        
        private bool cityIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal cinId {
            get {
                return this.cinIdField;
            }
            set {
                this.cinIdField = value;
                this.RaisePropertyChanged("cinId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinIdSpecified {
            get {
                return this.cinIdFieldSpecified;
            }
            set {
                this.cinIdFieldSpecified = value;
                this.RaisePropertyChanged("cinIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cinName {
            get {
                return this.cinNameField;
            }
            set {
                this.cinNameField = value;
                this.RaisePropertyChanged("cinName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] cinIcon {
            get {
                return this.cinIconField;
            }
            set {
                this.cinIconField = value;
                this.RaisePropertyChanged("cinIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cinAddress {
            get {
                return this.cinAddressField;
            }
            set {
                this.cinAddressField = value;
                this.RaisePropertyChanged("cinAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("halls", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public hall[] halls {
            get {
                return this.hallsField;
            }
            set {
                this.hallsField = value;
                this.RaisePropertyChanged("halls");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal cityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
                this.RaisePropertyChanged("cityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cityIdSpecified {
            get {
                return this.cityIdFieldSpecified;
            }
            set {
                this.cityIdFieldSpecified = value;
                this.RaisePropertyChanged("cityIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class hall : baseModel {
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        private string halNameField;
        
        private decimal halSitscountField;
        
        private bool halSitscountFieldSpecified;
        
        private floor[] floorsField;
        
        private decimal cinemaIdField;
        
        private bool cinemaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string halName {
            get {
                return this.halNameField;
            }
            set {
                this.halNameField = value;
                this.RaisePropertyChanged("halName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal halSitscount {
            get {
                return this.halSitscountField;
            }
            set {
                this.halSitscountField = value;
                this.RaisePropertyChanged("halSitscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halSitscountSpecified {
            get {
                return this.halSitscountFieldSpecified;
            }
            set {
                this.halSitscountFieldSpecified = value;
                this.RaisePropertyChanged("halSitscountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("floors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public floor[] floors {
            get {
                return this.floorsField;
            }
            set {
                this.floorsField = value;
                this.RaisePropertyChanged("floors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal cinemaId {
            get {
                return this.cinemaIdField;
            }
            set {
                this.cinemaIdField = value;
                this.RaisePropertyChanged("cinemaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinemaIdSpecified {
            get {
                return this.cinemaIdFieldSpecified;
            }
            set {
                this.cinemaIdFieldSpecified = value;
                this.RaisePropertyChanged("cinemaIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class floor : baseModel {
        
        private decimal flrIdField;
        
        private bool flrIdFieldSpecified;
        
        private string flrNameField;
        
        private decimal hallIdField;
        
        private bool hallIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal flrId {
            get {
                return this.flrIdField;
            }
            set {
                this.flrIdField = value;
                this.RaisePropertyChanged("flrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flrIdSpecified {
            get {
                return this.flrIdFieldSpecified;
            }
            set {
                this.flrIdFieldSpecified = value;
                this.RaisePropertyChanged("flrIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string flrName {
            get {
                return this.flrNameField;
            }
            set {
                this.flrNameField = value;
                this.RaisePropertyChanged("flrName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal hallId {
            get {
                return this.hallIdField;
            }
            set {
                this.hallIdField = value;
                this.RaisePropertyChanged("hallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hallIdSpecified {
            get {
                return this.hallIdFieldSpecified;
            }
            set {
                this.hallIdFieldSpecified = value;
                this.RaisePropertyChanged("hallIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(floor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hall))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cinema))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(city))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addCityRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeCityRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeCityRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class addCityRequest : baseDto {
        
        private string citNameField;
        
        private string citCountryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string citName {
            get {
                return this.citNameField;
            }
            set {
                this.citNameField = value;
                this.RaisePropertyChanged("citName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string citCountry {
            get {
                return this.citCountryField;
            }
            set {
                this.citCountryField = value;
                this.RaisePropertyChanged("citCountry");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class mergeCityRequest : addCityRequest {
        
        private decimal citIdField;
        
        private bool citIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal citId {
            get {
                return this.citIdField;
            }
            set {
                this.citIdField = value;
                this.RaisePropertyChanged("citId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool citIdSpecified {
            get {
                return this.citIdFieldSpecified;
            }
            set {
                this.citIdFieldSpecified = value;
                this.RaisePropertyChanged("citIdSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByName", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public findByNameRequest() {
        }
        
        public findByNameRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByNameResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CityService.city[] @return;
        
        public findByNameResponse() {
        }
        
        public findByNameResponse(EntertainmentNetwork.DAL.CityService.city[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCityById", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findCityByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findCityByIdRequest() {
        }
        
        public findCityByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCityByIdResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findCityByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CityService.city @return;
        
        public findCityByIdResponse() {
        }
        
        public findCityByIdResponse(EntertainmentNetwork.DAL.CityService.city @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeCity", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeCityRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CityService.mergeCityRequest arg0;
        
        public mergeCityRequest1() {
        }
        
        public mergeCityRequest1(EntertainmentNetwork.DAL.CityService.mergeCityRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeCityResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CityService.city @return;
        
        public mergeCityResponse() {
        }
        
        public mergeCityResponse(EntertainmentNetwork.DAL.CityService.city @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCities", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getCitiesRequest {
        
        public getCitiesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCitiesResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CityService.city[] @return;
        
        public getCitiesResponse() {
        }
        
        public getCitiesResponse(EntertainmentNetwork.DAL.CityService.city[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeCity", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeCityRequest() {
        }
        
        public removeCityRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeCityResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeCityResponse {
        
        public removeCityResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCity", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addCityRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CityService.addCityRequest arg0;
        
        public addCityRequest1() {
        }
        
        public addCityRequest1(EntertainmentNetwork.DAL.CityService.addCityRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCityResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addCityResponse {
        
        public addCityResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICityServiceChannel : EntertainmentNetwork.DAL.CityService.ICityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CityServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.CityService.ICityService>, EntertainmentNetwork.DAL.CityService.ICityService {
        
        public CityServiceClient() {
        }
        
        public CityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CityService.findByNameResponse EntertainmentNetwork.DAL.CityService.ICityService.findByName(EntertainmentNetwork.DAL.CityService.findByNameRequest request) {
            return base.Channel.findByName(request);
        }
        
        public EntertainmentNetwork.DAL.CityService.city[] findByName(string arg0) {
            EntertainmentNetwork.DAL.CityService.findByNameRequest inValue = new EntertainmentNetwork.DAL.CityService.findByNameRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CityService.findByNameResponse retVal = ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).findByName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.findByNameResponse> EntertainmentNetwork.DAL.CityService.ICityService.findByNameAsync(EntertainmentNetwork.DAL.CityService.findByNameRequest request) {
            return base.Channel.findByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.findByNameResponse> findByNameAsync(string arg0) {
            EntertainmentNetwork.DAL.CityService.findByNameRequest inValue = new EntertainmentNetwork.DAL.CityService.findByNameRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).findByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CityService.findCityByIdResponse EntertainmentNetwork.DAL.CityService.ICityService.findCityById(EntertainmentNetwork.DAL.CityService.findCityByIdRequest request) {
            return base.Channel.findCityById(request);
        }
        
        public EntertainmentNetwork.DAL.CityService.city findCityById(decimal arg0) {
            EntertainmentNetwork.DAL.CityService.findCityByIdRequest inValue = new EntertainmentNetwork.DAL.CityService.findCityByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CityService.findCityByIdResponse retVal = ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).findCityById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.findCityByIdResponse> EntertainmentNetwork.DAL.CityService.ICityService.findCityByIdAsync(EntertainmentNetwork.DAL.CityService.findCityByIdRequest request) {
            return base.Channel.findCityByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.findCityByIdResponse> findCityByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.CityService.findCityByIdRequest inValue = new EntertainmentNetwork.DAL.CityService.findCityByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).findCityByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CityService.mergeCityResponse EntertainmentNetwork.DAL.CityService.ICityService.mergeCity(EntertainmentNetwork.DAL.CityService.mergeCityRequest1 request) {
            return base.Channel.mergeCity(request);
        }
        
        public EntertainmentNetwork.DAL.CityService.city mergeCity(EntertainmentNetwork.DAL.CityService.mergeCityRequest arg0) {
            EntertainmentNetwork.DAL.CityService.mergeCityRequest1 inValue = new EntertainmentNetwork.DAL.CityService.mergeCityRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CityService.mergeCityResponse retVal = ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).mergeCity(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.mergeCityResponse> EntertainmentNetwork.DAL.CityService.ICityService.mergeCityAsync(EntertainmentNetwork.DAL.CityService.mergeCityRequest1 request) {
            return base.Channel.mergeCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.mergeCityResponse> mergeCityAsync(EntertainmentNetwork.DAL.CityService.mergeCityRequest arg0) {
            EntertainmentNetwork.DAL.CityService.mergeCityRequest1 inValue = new EntertainmentNetwork.DAL.CityService.mergeCityRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).mergeCityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CityService.getCitiesResponse EntertainmentNetwork.DAL.CityService.ICityService.getCities(EntertainmentNetwork.DAL.CityService.getCitiesRequest request) {
            return base.Channel.getCities(request);
        }
        
        public EntertainmentNetwork.DAL.CityService.city[] getCities() {
            EntertainmentNetwork.DAL.CityService.getCitiesRequest inValue = new EntertainmentNetwork.DAL.CityService.getCitiesRequest();
            EntertainmentNetwork.DAL.CityService.getCitiesResponse retVal = ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).getCities(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.getCitiesResponse> EntertainmentNetwork.DAL.CityService.ICityService.getCitiesAsync(EntertainmentNetwork.DAL.CityService.getCitiesRequest request) {
            return base.Channel.getCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.getCitiesResponse> getCitiesAsync() {
            EntertainmentNetwork.DAL.CityService.getCitiesRequest inValue = new EntertainmentNetwork.DAL.CityService.getCitiesRequest();
            return ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).getCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CityService.removeCityResponse EntertainmentNetwork.DAL.CityService.ICityService.removeCity(EntertainmentNetwork.DAL.CityService.removeCityRequest request) {
            return base.Channel.removeCity(request);
        }
        
        public void removeCity(decimal arg0) {
            EntertainmentNetwork.DAL.CityService.removeCityRequest inValue = new EntertainmentNetwork.DAL.CityService.removeCityRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CityService.removeCityResponse retVal = ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).removeCity(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.removeCityResponse> EntertainmentNetwork.DAL.CityService.ICityService.removeCityAsync(EntertainmentNetwork.DAL.CityService.removeCityRequest request) {
            return base.Channel.removeCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.removeCityResponse> removeCityAsync(decimal arg0) {
            EntertainmentNetwork.DAL.CityService.removeCityRequest inValue = new EntertainmentNetwork.DAL.CityService.removeCityRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).removeCityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CityService.addCityResponse EntertainmentNetwork.DAL.CityService.ICityService.addCity(EntertainmentNetwork.DAL.CityService.addCityRequest1 request) {
            return base.Channel.addCity(request);
        }
        
        public void addCity(EntertainmentNetwork.DAL.CityService.addCityRequest arg0) {
            EntertainmentNetwork.DAL.CityService.addCityRequest1 inValue = new EntertainmentNetwork.DAL.CityService.addCityRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CityService.addCityResponse retVal = ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).addCity(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.addCityResponse> EntertainmentNetwork.DAL.CityService.ICityService.addCityAsync(EntertainmentNetwork.DAL.CityService.addCityRequest1 request) {
            return base.Channel.addCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CityService.addCityResponse> addCityAsync(EntertainmentNetwork.DAL.CityService.addCityRequest arg0) {
            EntertainmentNetwork.DAL.CityService.addCityRequest1 inValue = new EntertainmentNetwork.DAL.CityService.addCityRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CityService.ICityService)(this)).addCityAsync(inValue);
        }
    }
}
