//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.HallService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", ConfigurationName="HallService.IHallService")]
    public interface IHallService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/removeHallReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/removeHallRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EntertainmentNetwork.DAL.HallService.removeHallResponse removeHall(EntertainmentNetwork.DAL.HallService.removeHallRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/removeHallReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/removeHallRes" +
            "ponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.removeHallResponse> removeHallAsync(EntertainmentNetwork.DAL.HallService.removeHallRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/findHallByIdR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/findHallByIdR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.HallService.findHallByIdResponse findHallById(EntertainmentNetwork.DAL.HallService.findHallByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/findHallByIdR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/findHallByIdR" +
            "esponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.findHallByIdResponse> findHallByIdAsync(EntertainmentNetwork.DAL.HallService.findHallByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/getHallsReque" +
            "st", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/getHallsRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.HallService.getHallsResponse getHalls(EntertainmentNetwork.DAL.HallService.getHallsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/getHallsReque" +
            "st", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/getHallsRespo" +
            "nse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.getHallsResponse> getHallsAsync(EntertainmentNetwork.DAL.HallService.getHallsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/mergeHallRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/mergeHallResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.HallService.mergeHallResponse mergeHall(EntertainmentNetwork.DAL.HallService.mergeHallRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/mergeHallRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/mergeHallResp" +
            "onse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.mergeHallResponse> mergeHallAsync(EntertainmentNetwork.DAL.HallService.mergeHallRequest1 request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/addHallReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/addHallRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        EntertainmentNetwork.DAL.HallService.addHallResponse addHall(EntertainmentNetwork.DAL.HallService.addHallRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/addHallReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IHallService/addHallRespon" +
            "se")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.addHallResponse> addHallAsync(EntertainmentNetwork.DAL.HallService.addHallRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeHall", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeHallRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeHallRequest() {
        }
        
        public removeHallRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeHallResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeHallResponse {
        
        public removeHallResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class hall : baseModel {
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        private string halNameField;
        
        private decimal halSitscountField;
        
        private bool halSitscountFieldSpecified;
        
        private floor[] floorsField;
        
        private decimal cinemaIdField;
        
        private bool cinemaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string halName {
            get {
                return this.halNameField;
            }
            set {
                this.halNameField = value;
                this.RaisePropertyChanged("halName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal halSitscount {
            get {
                return this.halSitscountField;
            }
            set {
                this.halSitscountField = value;
                this.RaisePropertyChanged("halSitscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halSitscountSpecified {
            get {
                return this.halSitscountFieldSpecified;
            }
            set {
                this.halSitscountFieldSpecified = value;
                this.RaisePropertyChanged("halSitscountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("floors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public floor[] floors {
            get {
                return this.floorsField;
            }
            set {
                this.floorsField = value;
                this.RaisePropertyChanged("floors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal cinemaId {
            get {
                return this.cinemaIdField;
            }
            set {
                this.cinemaIdField = value;
                this.RaisePropertyChanged("cinemaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinemaIdSpecified {
            get {
                return this.cinemaIdFieldSpecified;
            }
            set {
                this.cinemaIdFieldSpecified = value;
                this.RaisePropertyChanged("cinemaIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class floor : baseModel {
        
        private decimal flrIdField;
        
        private bool flrIdFieldSpecified;
        
        private string flrNameField;
        
        private decimal hallIdField;
        
        private bool hallIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal flrId {
            get {
                return this.flrIdField;
            }
            set {
                this.flrIdField = value;
                this.RaisePropertyChanged("flrId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool flrIdSpecified {
            get {
                return this.flrIdFieldSpecified;
            }
            set {
                this.flrIdFieldSpecified = value;
                this.RaisePropertyChanged("flrIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string flrName {
            get {
                return this.flrNameField;
            }
            set {
                this.flrNameField = value;
                this.RaisePropertyChanged("flrName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal hallId {
            get {
                return this.hallIdField;
            }
            set {
                this.hallIdField = value;
                this.RaisePropertyChanged("hallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hallIdSpecified {
            get {
                return this.hallIdFieldSpecified;
            }
            set {
                this.hallIdFieldSpecified = value;
                this.RaisePropertyChanged("hallIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(floor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hall))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addHallRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeHallRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeHallRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class addHallRequest : baseDto {
        
        private decimal cinIdField;
        
        private bool cinIdFieldSpecified;
        
        private string halNameField;
        
        private decimal halSitscountField;
        
        private bool halSitscountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal cinId {
            get {
                return this.cinIdField;
            }
            set {
                this.cinIdField = value;
                this.RaisePropertyChanged("cinId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinIdSpecified {
            get {
                return this.cinIdFieldSpecified;
            }
            set {
                this.cinIdFieldSpecified = value;
                this.RaisePropertyChanged("cinIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string halName {
            get {
                return this.halNameField;
            }
            set {
                this.halNameField = value;
                this.RaisePropertyChanged("halName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal halSitscount {
            get {
                return this.halSitscountField;
            }
            set {
                this.halSitscountField = value;
                this.RaisePropertyChanged("halSitscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halSitscountSpecified {
            get {
                return this.halSitscountFieldSpecified;
            }
            set {
                this.halSitscountFieldSpecified = value;
                this.RaisePropertyChanged("halSitscountSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class mergeHallRequest : addHallRequest {
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findHallById", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findHallByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findHallByIdRequest() {
        }
        
        public findHallByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findHallByIdResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findHallByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.HallService.hall @return;
        
        public findHallByIdResponse() {
        }
        
        public findHallByIdResponse(EntertainmentNetwork.DAL.HallService.hall @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHalls", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getHallsRequest {
        
        public getHallsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHallsResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getHallsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.HallService.hall[] @return;
        
        public getHallsResponse() {
        }
        
        public getHallsResponse(EntertainmentNetwork.DAL.HallService.hall[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeHall", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeHallRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.HallService.mergeHallRequest arg0;
        
        public mergeHallRequest1() {
        }
        
        public mergeHallRequest1(EntertainmentNetwork.DAL.HallService.mergeHallRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeHallResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeHallResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.HallService.hall @return;
        
        public mergeHallResponse() {
        }
        
        public mergeHallResponse(EntertainmentNetwork.DAL.HallService.hall @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addHall", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addHallRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.HallService.addHallRequest arg0;
        
        public addHallRequest1() {
        }
        
        public addHallRequest1(EntertainmentNetwork.DAL.HallService.addHallRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addHallResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addHallResponse {
        
        public addHallResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHallServiceChannel : EntertainmentNetwork.DAL.HallService.IHallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HallServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.HallService.IHallService>, EntertainmentNetwork.DAL.HallService.IHallService {
        
        public HallServiceClient() {
        }
        
        public HallServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HallServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HallServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HallServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.HallService.removeHallResponse EntertainmentNetwork.DAL.HallService.IHallService.removeHall(EntertainmentNetwork.DAL.HallService.removeHallRequest request) {
            return base.Channel.removeHall(request);
        }
        
        public void removeHall(decimal arg0) {
            EntertainmentNetwork.DAL.HallService.removeHallRequest inValue = new EntertainmentNetwork.DAL.HallService.removeHallRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.HallService.removeHallResponse retVal = ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).removeHall(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.removeHallResponse> EntertainmentNetwork.DAL.HallService.IHallService.removeHallAsync(EntertainmentNetwork.DAL.HallService.removeHallRequest request) {
            return base.Channel.removeHallAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.removeHallResponse> removeHallAsync(decimal arg0) {
            EntertainmentNetwork.DAL.HallService.removeHallRequest inValue = new EntertainmentNetwork.DAL.HallService.removeHallRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).removeHallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.HallService.findHallByIdResponse EntertainmentNetwork.DAL.HallService.IHallService.findHallById(EntertainmentNetwork.DAL.HallService.findHallByIdRequest request) {
            return base.Channel.findHallById(request);
        }
        
        public EntertainmentNetwork.DAL.HallService.hall findHallById(decimal arg0) {
            EntertainmentNetwork.DAL.HallService.findHallByIdRequest inValue = new EntertainmentNetwork.DAL.HallService.findHallByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.HallService.findHallByIdResponse retVal = ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).findHallById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.findHallByIdResponse> EntertainmentNetwork.DAL.HallService.IHallService.findHallByIdAsync(EntertainmentNetwork.DAL.HallService.findHallByIdRequest request) {
            return base.Channel.findHallByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.findHallByIdResponse> findHallByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.HallService.findHallByIdRequest inValue = new EntertainmentNetwork.DAL.HallService.findHallByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).findHallByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.HallService.getHallsResponse EntertainmentNetwork.DAL.HallService.IHallService.getHalls(EntertainmentNetwork.DAL.HallService.getHallsRequest request) {
            return base.Channel.getHalls(request);
        }
        
        public EntertainmentNetwork.DAL.HallService.hall[] getHalls() {
            EntertainmentNetwork.DAL.HallService.getHallsRequest inValue = new EntertainmentNetwork.DAL.HallService.getHallsRequest();
            EntertainmentNetwork.DAL.HallService.getHallsResponse retVal = ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).getHalls(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.getHallsResponse> EntertainmentNetwork.DAL.HallService.IHallService.getHallsAsync(EntertainmentNetwork.DAL.HallService.getHallsRequest request) {
            return base.Channel.getHallsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.getHallsResponse> getHallsAsync() {
            EntertainmentNetwork.DAL.HallService.getHallsRequest inValue = new EntertainmentNetwork.DAL.HallService.getHallsRequest();
            return ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).getHallsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.HallService.mergeHallResponse EntertainmentNetwork.DAL.HallService.IHallService.mergeHall(EntertainmentNetwork.DAL.HallService.mergeHallRequest1 request) {
            return base.Channel.mergeHall(request);
        }
        
        public EntertainmentNetwork.DAL.HallService.hall mergeHall(EntertainmentNetwork.DAL.HallService.mergeHallRequest arg0) {
            EntertainmentNetwork.DAL.HallService.mergeHallRequest1 inValue = new EntertainmentNetwork.DAL.HallService.mergeHallRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.HallService.mergeHallResponse retVal = ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).mergeHall(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.mergeHallResponse> EntertainmentNetwork.DAL.HallService.IHallService.mergeHallAsync(EntertainmentNetwork.DAL.HallService.mergeHallRequest1 request) {
            return base.Channel.mergeHallAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.mergeHallResponse> mergeHallAsync(EntertainmentNetwork.DAL.HallService.mergeHallRequest arg0) {
            EntertainmentNetwork.DAL.HallService.mergeHallRequest1 inValue = new EntertainmentNetwork.DAL.HallService.mergeHallRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).mergeHallAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.HallService.addHallResponse EntertainmentNetwork.DAL.HallService.IHallService.addHall(EntertainmentNetwork.DAL.HallService.addHallRequest1 request) {
            return base.Channel.addHall(request);
        }
        
        public void addHall(EntertainmentNetwork.DAL.HallService.addHallRequest arg0) {
            EntertainmentNetwork.DAL.HallService.addHallRequest1 inValue = new EntertainmentNetwork.DAL.HallService.addHallRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.HallService.addHallResponse retVal = ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).addHall(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.addHallResponse> EntertainmentNetwork.DAL.HallService.IHallService.addHallAsync(EntertainmentNetwork.DAL.HallService.addHallRequest1 request) {
            return base.Channel.addHallAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.HallService.addHallResponse> addHallAsync(EntertainmentNetwork.DAL.HallService.addHallRequest arg0) {
            EntertainmentNetwork.DAL.HallService.addHallRequest1 inValue = new EntertainmentNetwork.DAL.HallService.addHallRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.HallService.IHallService)(this)).addHallAsync(inValue);
        }
    }
}
