//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetworkClient.SitService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", ConfigurationName="SitService.ISitService")]
    public interface ISitService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/getSitsRequest" +
            "", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/getSitsRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetworkClient.SitService.getSitsResponse getSits(EntertainmentNetworkClient.SitService.getSitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/getSitsRequest" +
            "", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/getSitsRespons" +
            "e")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.getSitsResponse> getSitsAsync(EntertainmentNetworkClient.SitService.getSitsRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/removeSitReque" +
            "st", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/removeSitRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        EntertainmentNetworkClient.SitService.removeSitResponse removeSit(EntertainmentNetworkClient.SitService.removeSitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/removeSitReque" +
            "st", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/removeSitRespo" +
            "nse")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.removeSitResponse> removeSitAsync(EntertainmentNetworkClient.SitService.removeSitRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/mergeSitReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/mergeSitRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetworkClient.SitService.mergeSitResponse mergeSit(EntertainmentNetworkClient.SitService.mergeSitRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/mergeSitReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/mergeSitRespon" +
            "se")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.mergeSitResponse> mergeSitAsync(EntertainmentNetworkClient.SitService.mergeSitRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/findSitByIdReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/findSitByIdRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetworkClient.SitService.findSitByIdResponse findSitById(EntertainmentNetworkClient.SitService.findSitByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/findSitByIdReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/findSitByIdRes" +
            "ponse")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.findSitByIdResponse> findSitByIdAsync(EntertainmentNetworkClient.SitService.findSitByIdRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/addSitRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/addSitResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        EntertainmentNetworkClient.SitService.addSitResponse addSit(EntertainmentNetworkClient.SitService.addSitRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/addSitRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISitService/addSitResponse" +
            "")]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.addSitResponse> addSitAsync(EntertainmentNetworkClient.SitService.addSitRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class sit : baseModel {
        
        private decimal sitIdField;
        
        private bool sitIdFieldSpecified;
        
        private decimal sitNumField;
        
        private bool sitNumFieldSpecified;
        
        private decimal sitRowField;
        
        private bool sitRowFieldSpecified;
        
        private decimal sitFloorField;
        
        private bool sitFloorFieldSpecified;
        
        private decimal sitTypeField;
        
        private bool sitTypeFieldSpecified;
        
        private decimal cinemaIdField;
        
        private bool cinemaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal sitId {
            get {
                return this.sitIdField;
            }
            set {
                this.sitIdField = value;
                this.RaisePropertyChanged("sitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitIdSpecified {
            get {
                return this.sitIdFieldSpecified;
            }
            set {
                this.sitIdFieldSpecified = value;
                this.RaisePropertyChanged("sitIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal sitNum {
            get {
                return this.sitNumField;
            }
            set {
                this.sitNumField = value;
                this.RaisePropertyChanged("sitNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitNumSpecified {
            get {
                return this.sitNumFieldSpecified;
            }
            set {
                this.sitNumFieldSpecified = value;
                this.RaisePropertyChanged("sitNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal sitRow {
            get {
                return this.sitRowField;
            }
            set {
                this.sitRowField = value;
                this.RaisePropertyChanged("sitRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitRowSpecified {
            get {
                return this.sitRowFieldSpecified;
            }
            set {
                this.sitRowFieldSpecified = value;
                this.RaisePropertyChanged("sitRowSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal sitFloor {
            get {
                return this.sitFloorField;
            }
            set {
                this.sitFloorField = value;
                this.RaisePropertyChanged("sitFloor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitFloorSpecified {
            get {
                return this.sitFloorFieldSpecified;
            }
            set {
                this.sitFloorFieldSpecified = value;
                this.RaisePropertyChanged("sitFloorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal sitType {
            get {
                return this.sitTypeField;
            }
            set {
                this.sitTypeField = value;
                this.RaisePropertyChanged("sitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitTypeSpecified {
            get {
                return this.sitTypeFieldSpecified;
            }
            set {
                this.sitTypeFieldSpecified = value;
                this.RaisePropertyChanged("sitTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal cinemaId {
            get {
                return this.cinemaIdField;
            }
            set {
                this.cinemaIdField = value;
                this.RaisePropertyChanged("cinemaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinemaIdSpecified {
            get {
                return this.cinemaIdFieldSpecified;
            }
            set {
                this.cinemaIdFieldSpecified = value;
                this.RaisePropertyChanged("cinemaIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sit))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addSitRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeSitRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeSitRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class addSitRequest : baseDto {
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        private decimal sitNumField;
        
        private bool sitNumFieldSpecified;
        
        private decimal sitRowField;
        
        private bool sitRowFieldSpecified;
        
        private decimal sitFloorField;
        
        private bool sitFloorFieldSpecified;
        
        private decimal sitTypeField;
        
        private bool sitTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal sitNum {
            get {
                return this.sitNumField;
            }
            set {
                this.sitNumField = value;
                this.RaisePropertyChanged("sitNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitNumSpecified {
            get {
                return this.sitNumFieldSpecified;
            }
            set {
                this.sitNumFieldSpecified = value;
                this.RaisePropertyChanged("sitNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal sitRow {
            get {
                return this.sitRowField;
            }
            set {
                this.sitRowField = value;
                this.RaisePropertyChanged("sitRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitRowSpecified {
            get {
                return this.sitRowFieldSpecified;
            }
            set {
                this.sitRowFieldSpecified = value;
                this.RaisePropertyChanged("sitRowSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal sitFloor {
            get {
                return this.sitFloorField;
            }
            set {
                this.sitFloorField = value;
                this.RaisePropertyChanged("sitFloor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitFloorSpecified {
            get {
                return this.sitFloorFieldSpecified;
            }
            set {
                this.sitFloorFieldSpecified = value;
                this.RaisePropertyChanged("sitFloorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal sitType {
            get {
                return this.sitTypeField;
            }
            set {
                this.sitTypeField = value;
                this.RaisePropertyChanged("sitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitTypeSpecified {
            get {
                return this.sitTypeFieldSpecified;
            }
            set {
                this.sitTypeFieldSpecified = value;
                this.RaisePropertyChanged("sitTypeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class mergeSitRequest : addSitRequest {
        
        private decimal sitIdField;
        
        private bool sitIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal sitId {
            get {
                return this.sitIdField;
            }
            set {
                this.sitIdField = value;
                this.RaisePropertyChanged("sitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitIdSpecified {
            get {
                return this.sitIdFieldSpecified;
            }
            set {
                this.sitIdFieldSpecified = value;
                this.RaisePropertyChanged("sitIdSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSits", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getSitsRequest {
        
        public getSitsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSitsResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getSitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.SitService.sit[] @return;
        
        public getSitsResponse() {
        }
        
        public getSitsResponse(EntertainmentNetworkClient.SitService.sit[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeSit", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeSitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeSitRequest() {
        }
        
        public removeSitRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeSitResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeSitResponse {
        
        public removeSitResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeSit", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeSitRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.SitService.mergeSitRequest arg0;
        
        public mergeSitRequest1() {
        }
        
        public mergeSitRequest1(EntertainmentNetworkClient.SitService.mergeSitRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeSitResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeSitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.SitService.sit @return;
        
        public mergeSitResponse() {
        }
        
        public mergeSitResponse(EntertainmentNetworkClient.SitService.sit @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findSitById", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findSitByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findSitByIdRequest() {
        }
        
        public findSitByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findSitByIdResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findSitByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.SitService.sit @return;
        
        public findSitByIdResponse() {
        }
        
        public findSitByIdResponse(EntertainmentNetworkClient.SitService.sit @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addSit", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addSitRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetworkClient.SitService.addSitRequest arg0;
        
        public addSitRequest1() {
        }
        
        public addSitRequest1(EntertainmentNetworkClient.SitService.addSitRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addSitResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addSitResponse {
        
        public addSitResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISitServiceChannel : EntertainmentNetworkClient.SitService.ISitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SitServiceClient : System.ServiceModel.ClientBase<EntertainmentNetworkClient.SitService.ISitService>, EntertainmentNetworkClient.SitService.ISitService {
        
        public SitServiceClient() {
        }
        
        public SitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.SitService.getSitsResponse EntertainmentNetworkClient.SitService.ISitService.getSits(EntertainmentNetworkClient.SitService.getSitsRequest request) {
            return base.Channel.getSits(request);
        }
        
        public EntertainmentNetworkClient.SitService.sit[] getSits() {
            EntertainmentNetworkClient.SitService.getSitsRequest inValue = new EntertainmentNetworkClient.SitService.getSitsRequest();
            EntertainmentNetworkClient.SitService.getSitsResponse retVal = ((EntertainmentNetworkClient.SitService.ISitService)(this)).getSits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.getSitsResponse> EntertainmentNetworkClient.SitService.ISitService.getSitsAsync(EntertainmentNetworkClient.SitService.getSitsRequest request) {
            return base.Channel.getSitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.getSitsResponse> getSitsAsync() {
            EntertainmentNetworkClient.SitService.getSitsRequest inValue = new EntertainmentNetworkClient.SitService.getSitsRequest();
            return ((EntertainmentNetworkClient.SitService.ISitService)(this)).getSitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.SitService.removeSitResponse EntertainmentNetworkClient.SitService.ISitService.removeSit(EntertainmentNetworkClient.SitService.removeSitRequest request) {
            return base.Channel.removeSit(request);
        }
        
        public void removeSit(decimal arg0) {
            EntertainmentNetworkClient.SitService.removeSitRequest inValue = new EntertainmentNetworkClient.SitService.removeSitRequest();
            inValue.arg0 = arg0;
            EntertainmentNetworkClient.SitService.removeSitResponse retVal = ((EntertainmentNetworkClient.SitService.ISitService)(this)).removeSit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.removeSitResponse> EntertainmentNetworkClient.SitService.ISitService.removeSitAsync(EntertainmentNetworkClient.SitService.removeSitRequest request) {
            return base.Channel.removeSitAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.removeSitResponse> removeSitAsync(decimal arg0) {
            EntertainmentNetworkClient.SitService.removeSitRequest inValue = new EntertainmentNetworkClient.SitService.removeSitRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetworkClient.SitService.ISitService)(this)).removeSitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.SitService.mergeSitResponse EntertainmentNetworkClient.SitService.ISitService.mergeSit(EntertainmentNetworkClient.SitService.mergeSitRequest1 request) {
            return base.Channel.mergeSit(request);
        }
        
        public EntertainmentNetworkClient.SitService.sit mergeSit(EntertainmentNetworkClient.SitService.mergeSitRequest arg0) {
            EntertainmentNetworkClient.SitService.mergeSitRequest1 inValue = new EntertainmentNetworkClient.SitService.mergeSitRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetworkClient.SitService.mergeSitResponse retVal = ((EntertainmentNetworkClient.SitService.ISitService)(this)).mergeSit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.mergeSitResponse> EntertainmentNetworkClient.SitService.ISitService.mergeSitAsync(EntertainmentNetworkClient.SitService.mergeSitRequest1 request) {
            return base.Channel.mergeSitAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.mergeSitResponse> mergeSitAsync(EntertainmentNetworkClient.SitService.mergeSitRequest arg0) {
            EntertainmentNetworkClient.SitService.mergeSitRequest1 inValue = new EntertainmentNetworkClient.SitService.mergeSitRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetworkClient.SitService.ISitService)(this)).mergeSitAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.SitService.findSitByIdResponse EntertainmentNetworkClient.SitService.ISitService.findSitById(EntertainmentNetworkClient.SitService.findSitByIdRequest request) {
            return base.Channel.findSitById(request);
        }
        
        public EntertainmentNetworkClient.SitService.sit findSitById(decimal arg0) {
            EntertainmentNetworkClient.SitService.findSitByIdRequest inValue = new EntertainmentNetworkClient.SitService.findSitByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetworkClient.SitService.findSitByIdResponse retVal = ((EntertainmentNetworkClient.SitService.ISitService)(this)).findSitById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.findSitByIdResponse> EntertainmentNetworkClient.SitService.ISitService.findSitByIdAsync(EntertainmentNetworkClient.SitService.findSitByIdRequest request) {
            return base.Channel.findSitByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.findSitByIdResponse> findSitByIdAsync(decimal arg0) {
            EntertainmentNetworkClient.SitService.findSitByIdRequest inValue = new EntertainmentNetworkClient.SitService.findSitByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetworkClient.SitService.ISitService)(this)).findSitByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetworkClient.SitService.addSitResponse EntertainmentNetworkClient.SitService.ISitService.addSit(EntertainmentNetworkClient.SitService.addSitRequest1 request) {
            return base.Channel.addSit(request);
        }
        
        public void addSit(EntertainmentNetworkClient.SitService.addSitRequest arg0) {
            EntertainmentNetworkClient.SitService.addSitRequest1 inValue = new EntertainmentNetworkClient.SitService.addSitRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetworkClient.SitService.addSitResponse retVal = ((EntertainmentNetworkClient.SitService.ISitService)(this)).addSit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.addSitResponse> EntertainmentNetworkClient.SitService.ISitService.addSitAsync(EntertainmentNetworkClient.SitService.addSitRequest1 request) {
            return base.Channel.addSitAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetworkClient.SitService.addSitResponse> addSitAsync(EntertainmentNetworkClient.SitService.addSitRequest arg0) {
            EntertainmentNetworkClient.SitService.addSitRequest1 inValue = new EntertainmentNetworkClient.SitService.addSitRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetworkClient.SitService.ISitService)(this)).addSitAsync(inValue);
        }
    }
}
