
--------------------------------------------------------
--  DDL for Sequences
--------------------------------------------------------
   CREATE SEQUENCE  "PBAB"."CINEMA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "PBAB"."CITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "PBAB"."HALL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "PBAB"."SIT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "PBAB"."CITY" 
   (	"CIT_ID" NUMBER NOT NULL,
	"CIT_NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"CIT_COUNTRY" VARCHAR2(100 BYTE) NOT NULL,
	CONSTRAINT "CITY_PK" PRIMARY KEY ("CIT_ID")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  --------------------------------------------------------
--  DDL for Table CINEMA
--------------------------------------------------------

  CREATE TABLE "PBAB"."CINEMA" 
   (	"CIN_ID" NUMBER NOT NULL, 
	"CIN_NAME" VARCHAR2(100 BYTE) NOT NULL,
	"CIN_ICON" BLOB, 
	"CIN_ADDRESS" VARCHAR2(255 BYTE) NOT NULL,
	"CIN_CITY_ID" NUMBER NOT NULL,
	CONSTRAINT "CINEMA_PK" PRIMARY KEY ("CIN_ID"),
	CONSTRAINT "CINEMA_FK" FOREIGN KEY ("CIN_CITY_ID") REFERENCES "PBAB"."CITY" ("CIT_ID")
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CIN_ICON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  
--------------------------------------------------------
--  DDL for Table HALL
--------------------------------------------------------

  CREATE TABLE "PBAB"."HALL" 
   (	"HAL_ID" NUMBER NOT NULL,
	"HAL_CIN_ID" NUMBER NOT NULL,
	"HAL_NAME" VARCHAR2(100 BYTE) NOT NULL,
	"HAL_SITSCOUNT" NUMBER NOT NULL,
	CONSTRAINT "HALL_PK" PRIMARY KEY ("HAL_ID"),
	CONSTRAINT "HALL_FK" FOREIGN KEY ("HAL_CIN_ID") REFERENCES "PBAB"."CINEMA" ("CIN_ID")
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SIT
--------------------------------------------------------

  CREATE TABLE "PBAB"."SIT" 
   (	"SIT_ID" NUMBER NOT NULL,
	"SIT_HAL_ID" NUMBER NOT NULL,
	"SIT_NUM" NUMBER NOT NULL,
	"SIT_ROW" NUMBER NOT NULL,
	"SIT_FLOOR" NUMBER NOT NULL,
	"SIT_TYPE" NUMBER NOT NULL,
	CONSTRAINT "SIT_PK" PRIMARY KEY ("SIT_ID"),
	CONSTRAINT "SIT_FK" FOREIGN KEY ("SIT_HAL_ID") REFERENCES "PBAB"."HALL" ("HAL_ID")
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Index SIT_UNIQ
--------------------------------------------------------

  CREATE UNIQUE INDEX "PBAB"."SIT_UNIQ" ON "PBAB"."SIT" ("SIT_ROW", "SIT_FLOOR", "SIT_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Trigger CINEMA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PBAB"."CINEMA_TRG" 
BEFORE INSERT ON CINEMA 
FOR EACH ROW

BEGIN
  SELECT CINEMA_SEQ.NEXTVAL
  INTO   :new.CIN_ID
  FROM   dual;
END;
/
ALTER TRIGGER "PBAB"."CINEMA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CITY_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PBAB"."CITY_TRG" 
BEFORE INSERT ON CITY 
FOR EACH ROW

BEGIN
  SELECT CITY_SEQ.NEXTVAL
  INTO   :new.CIT_ID
  FROM   dual;
END;
/
ALTER TRIGGER "PBAB"."CITY_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HALL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PBAB"."HALL_TRG" 
BEFORE INSERT ON HALL 
FOR EACH ROW

BEGIN
  SELECT HALL_SEQ.NEXTVAL
  INTO   :new.HAL_ID
  FROM   dual;
END;
/
ALTER TRIGGER "PBAB"."HALL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SIT_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "PBAB"."SIT_TRG" 
BEFORE INSERT ON SIT 
FOR EACH ROW

BEGIN
  SELECT CINEMA_SEQ.NEXTVAL
  INTO   :new.SIT_ID
  FROM   dual;
END;
/
ALTER TRIGGER "PBAB"."SIT_TRG" ENABLE;
