//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.SchedulerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", ConfigurationName="SchedulerService.ISchedulerService")]
    public interface ISchedulerService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/mergeSch" +
            "edulerRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/mergeSch" +
            "edulerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerResponse mergeScheduler(EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/mergeSch" +
            "edulerRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/mergeSch" +
            "edulerResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerResponse> mergeSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest1 request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/removeSc" +
            "hedulerRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/removeSc" +
            "hedulerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse removeScheduler(EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/removeSc" +
            "hedulerRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/removeSc" +
            "hedulerResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse> removeSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/addSched" +
            "ulerRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/addSched" +
            "ulerResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        EntertainmentNetwork.DAL.SchedulerService.addSchedulerResponse addScheduler(EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/addSched" +
            "ulerRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/addSched" +
            "ulerResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.addSchedulerResponse> addSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/getSched" +
            "ulersRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/getSched" +
            "ulersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse getSchedulers(EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/getSched" +
            "ulersRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/getSched" +
            "ulersResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse> getSchedulersAsync(EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/findSche" +
            "dulerByIdRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/findSche" +
            "dulerByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse findSchedulerById(EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/findSche" +
            "dulerByIdRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ISchedulerService/findSche" +
            "dulerByIdResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse> findSchedulerByIdAsync(EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class mergeSchedulerRequest : addSchedulerRequest {
        
        private decimal schIdField;
        
        private bool schIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal schId {
            get {
                return this.schIdField;
            }
            set {
                this.schIdField = value;
                this.RaisePropertyChanged("schId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schIdSpecified {
            get {
                return this.schIdFieldSpecified;
            }
            set {
                this.schIdFieldSpecified = value;
                this.RaisePropertyChanged("schIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeSchedulerRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class addSchedulerRequest : baseDto {
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        private string schDescrField;
        
        private string schNameField;
        
        private System.DateTime schTimeFromField;
        
        private bool schTimeFromFieldSpecified;
        
        private System.DateTime schTimeToField;
        
        private bool schTimeToFieldSpecified;
        
        private decimal shwIdField;
        
        private bool shwIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string schDescr {
            get {
                return this.schDescrField;
            }
            set {
                this.schDescrField = value;
                this.RaisePropertyChanged("schDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string schName {
            get {
                return this.schNameField;
            }
            set {
                this.schNameField = value;
                this.RaisePropertyChanged("schName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime schTimeFrom {
            get {
                return this.schTimeFromField;
            }
            set {
                this.schTimeFromField = value;
                this.RaisePropertyChanged("schTimeFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeFromSpecified {
            get {
                return this.schTimeFromFieldSpecified;
            }
            set {
                this.schTimeFromFieldSpecified = value;
                this.RaisePropertyChanged("schTimeFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime schTimeTo {
            get {
                return this.schTimeToField;
            }
            set {
                this.schTimeToField = value;
                this.RaisePropertyChanged("schTimeTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeToSpecified {
            get {
                return this.schTimeToFieldSpecified;
            }
            set {
                this.schTimeToFieldSpecified = value;
                this.RaisePropertyChanged("schTimeToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal shwId {
            get {
                return this.shwIdField;
            }
            set {
                this.shwIdField = value;
                this.RaisePropertyChanged("shwId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shwIdSpecified {
            get {
                return this.shwIdFieldSpecified;
            }
            set {
                this.shwIdFieldSpecified = value;
                this.RaisePropertyChanged("shwIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addSchedulerRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeSchedulerRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(scheduler))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class scheduler : baseModel {
        
        private decimal schIdField;
        
        private bool schIdFieldSpecified;
        
        private string schNameField;
        
        private string schDescrField;
        
        private System.DateTime schTimeFromField;
        
        private bool schTimeFromFieldSpecified;
        
        private System.DateTime schTimeToField;
        
        private bool schTimeToFieldSpecified;
        
        private decimal hallIdField;
        
        private bool hallIdFieldSpecified;
        
        private decimal showIdField;
        
        private bool showIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal schId {
            get {
                return this.schIdField;
            }
            set {
                this.schIdField = value;
                this.RaisePropertyChanged("schId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schIdSpecified {
            get {
                return this.schIdFieldSpecified;
            }
            set {
                this.schIdFieldSpecified = value;
                this.RaisePropertyChanged("schIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string schName {
            get {
                return this.schNameField;
            }
            set {
                this.schNameField = value;
                this.RaisePropertyChanged("schName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string schDescr {
            get {
                return this.schDescrField;
            }
            set {
                this.schDescrField = value;
                this.RaisePropertyChanged("schDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime schTimeFrom {
            get {
                return this.schTimeFromField;
            }
            set {
                this.schTimeFromField = value;
                this.RaisePropertyChanged("schTimeFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeFromSpecified {
            get {
                return this.schTimeFromFieldSpecified;
            }
            set {
                this.schTimeFromFieldSpecified = value;
                this.RaisePropertyChanged("schTimeFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime schTimeTo {
            get {
                return this.schTimeToField;
            }
            set {
                this.schTimeToField = value;
                this.RaisePropertyChanged("schTimeTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeToSpecified {
            get {
                return this.schTimeToFieldSpecified;
            }
            set {
                this.schTimeToFieldSpecified = value;
                this.RaisePropertyChanged("schTimeToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal hallId {
            get {
                return this.hallIdField;
            }
            set {
                this.hallIdField = value;
                this.RaisePropertyChanged("hallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hallIdSpecified {
            get {
                return this.hallIdFieldSpecified;
            }
            set {
                this.hallIdFieldSpecified = value;
                this.RaisePropertyChanged("hallIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public decimal showId {
            get {
                return this.showIdField;
            }
            set {
                this.showIdField = value;
                this.RaisePropertyChanged("showId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showIdSpecified {
            get {
                return this.showIdFieldSpecified;
            }
            set {
                this.showIdFieldSpecified = value;
                this.RaisePropertyChanged("showIdSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeScheduler", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeSchedulerRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest arg0;
        
        public mergeSchedulerRequest1() {
        }
        
        public mergeSchedulerRequest1(EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeSchedulerResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeSchedulerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.scheduler @return;
        
        public mergeSchedulerResponse() {
        }
        
        public mergeSchedulerResponse(EntertainmentNetwork.DAL.SchedulerService.scheduler @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeScheduler", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeSchedulerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeSchedulerRequest() {
        }
        
        public removeSchedulerRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeSchedulerResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeSchedulerResponse {
        
        public removeSchedulerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addScheduler", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addSchedulerRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest arg0;
        
        public addSchedulerRequest1() {
        }
        
        public addSchedulerRequest1(EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addSchedulerResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addSchedulerResponse {
        
        public addSchedulerResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSchedulers", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getSchedulersRequest {
        
        public getSchedulersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSchedulersResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getSchedulersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return;
        
        public getSchedulersResponse() {
        }
        
        public getSchedulersResponse(EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findSchedulerById", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findSchedulerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findSchedulerByIdRequest() {
        }
        
        public findSchedulerByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findSchedulerByIdResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findSchedulerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.scheduler @return;
        
        public findSchedulerByIdResponse() {
        }
        
        public findSchedulerByIdResponse(EntertainmentNetwork.DAL.SchedulerService.scheduler @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchedulerServiceChannel : EntertainmentNetwork.DAL.SchedulerService.ISchedulerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulerServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.SchedulerService.ISchedulerService>, EntertainmentNetwork.DAL.SchedulerService.ISchedulerService {
        
        public SchedulerServiceClient() {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerResponse EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.mergeScheduler(EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest1 request) {
            return base.Channel.mergeScheduler(request);
        }
        
        public EntertainmentNetwork.DAL.SchedulerService.scheduler mergeScheduler(EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest arg0) {
            EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest1 inValue = new EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).mergeScheduler(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerResponse> EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.mergeSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest1 request) {
            return base.Channel.mergeSchedulerAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerResponse> mergeSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest arg0) {
            EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest1 inValue = new EntertainmentNetwork.DAL.SchedulerService.mergeSchedulerRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).mergeSchedulerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.removeScheduler(EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest request) {
            return base.Channel.removeScheduler(request);
        }
        
        public void removeScheduler(decimal arg0) {
            EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).removeScheduler(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse> EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.removeSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest request) {
            return base.Channel.removeSchedulerAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse> removeSchedulerAsync(decimal arg0) {
            EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).removeSchedulerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.addSchedulerResponse EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.addScheduler(EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest1 request) {
            return base.Channel.addScheduler(request);
        }
        
        public void addScheduler(EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest arg0) {
            EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest1 inValue = new EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.SchedulerService.addSchedulerResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).addScheduler(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.addSchedulerResponse> EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.addSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest1 request) {
            return base.Channel.addSchedulerAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.addSchedulerResponse> addSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest arg0) {
            EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest1 inValue = new EntertainmentNetwork.DAL.SchedulerService.addSchedulerRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).addSchedulerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.getSchedulers(EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest request) {
            return base.Channel.getSchedulers(request);
        }
        
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] getSchedulers() {
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest();
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).getSchedulers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse> EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.getSchedulersAsync(EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest request) {
            return base.Channel.getSchedulersAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse> getSchedulersAsync() {
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest();
            return ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).getSchedulersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.findSchedulerById(EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest request) {
            return base.Channel.findSchedulerById(request);
        }
        
        public EntertainmentNetwork.DAL.SchedulerService.scheduler findSchedulerById(decimal arg0) {
            EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).findSchedulerById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse> EntertainmentNetwork.DAL.SchedulerService.ISchedulerService.findSchedulerByIdAsync(EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest request) {
            return base.Channel.findSchedulerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse> findSchedulerByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.SchedulerService.ISchedulerService)(this)).findSchedulerByIdAsync(inValue);
        }
    }
}
