//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.ShowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", ConfigurationName="ShowService.IShowService")]
    public interface IShowService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/addShowReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/addShowRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        EntertainmentNetwork.DAL.ShowService.addShowResponse addShow(EntertainmentNetwork.DAL.ShowService.addShowRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/addShowReques" +
            "t", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/addShowRespon" +
            "se")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.addShowResponse> addShowAsync(EntertainmentNetwork.DAL.ShowService.addShowRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/findShowByIdR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/findShowByIdR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.ShowService.findShowByIdResponse findShowById(EntertainmentNetwork.DAL.ShowService.findShowByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/findShowByIdR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/findShowByIdR" +
            "esponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.findShowByIdResponse> findShowByIdAsync(EntertainmentNetwork.DAL.ShowService.findShowByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/mergeShowRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/mergeShowResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.ShowService.mergeShowResponse mergeShow(EntertainmentNetwork.DAL.ShowService.mergeShowRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/mergeShowRequ" +
            "est", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/mergeShowResp" +
            "onse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.mergeShowResponse> mergeShowAsync(EntertainmentNetwork.DAL.ShowService.mergeShowRequest1 request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/removeShowReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/removeShowRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        EntertainmentNetwork.DAL.ShowService.removeShowResponse removeShow(EntertainmentNetwork.DAL.ShowService.removeShowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/removeShowReq" +
            "uest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/removeShowRes" +
            "ponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.removeShowResponse> removeShowAsync(EntertainmentNetwork.DAL.ShowService.removeShowRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/getShowsReque" +
            "st", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/getShowsRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.ShowService.getShowsResponse getShows(EntertainmentNetwork.DAL.ShowService.getShowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/getShowsReque" +
            "st", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/IShowService/getShowsRespo" +
            "nse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getShowsResponse> getShowsAsync(EntertainmentNetwork.DAL.ShowService.getShowsRequest request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeShowRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class addShowRequest : baseDto {
        
        private string shwDescrField;
        
        private byte[] shwIconField;
        
        private string shwNameField;
        
        private string shwPerformerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string shwDescr {
            get {
                return this.shwDescrField;
            }
            set {
                this.shwDescrField = value;
                this.RaisePropertyChanged("shwDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] shwIcon {
            get {
                return this.shwIconField;
            }
            set {
                this.shwIconField = value;
                this.RaisePropertyChanged("shwIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string shwName {
            get {
                return this.shwNameField;
            }
            set {
                this.shwNameField = value;
                this.RaisePropertyChanged("shwName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string shwPerformer {
            get {
                return this.shwPerformerField;
            }
            set {
                this.shwPerformerField = value;
                this.RaisePropertyChanged("shwPerformer");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addShowRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeShowRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(show))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class show : baseModel {
        
        private decimal shwIdField;
        
        private bool shwIdFieldSpecified;
        
        private string shwNameField;
        
        private string shwPerformerField;
        
        private string shwDescrField;
        
        private byte[] shwIconField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal shwId {
            get {
                return this.shwIdField;
            }
            set {
                this.shwIdField = value;
                this.RaisePropertyChanged("shwId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shwIdSpecified {
            get {
                return this.shwIdFieldSpecified;
            }
            set {
                this.shwIdFieldSpecified = value;
                this.RaisePropertyChanged("shwIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string shwName {
            get {
                return this.shwNameField;
            }
            set {
                this.shwNameField = value;
                this.RaisePropertyChanged("shwName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string shwPerformer {
            get {
                return this.shwPerformerField;
            }
            set {
                this.shwPerformerField = value;
                this.RaisePropertyChanged("shwPerformer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string shwDescr {
            get {
                return this.shwDescrField;
            }
            set {
                this.shwDescrField = value;
                this.RaisePropertyChanged("shwDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] shwIcon {
            get {
                return this.shwIconField;
            }
            set {
                this.shwIconField = value;
                this.RaisePropertyChanged("shwIcon");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class mergeShowRequest : addShowRequest {
        
        private decimal shwIdField;
        
        private bool shwIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal shwId {
            get {
                return this.shwIdField;
            }
            set {
                this.shwIdField = value;
                this.RaisePropertyChanged("shwId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shwIdSpecified {
            get {
                return this.shwIdFieldSpecified;
            }
            set {
                this.shwIdFieldSpecified = value;
                this.RaisePropertyChanged("shwIdSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addShow", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addShowRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.addShowRequest arg0;
        
        public addShowRequest1() {
        }
        
        public addShowRequest1(EntertainmentNetwork.DAL.ShowService.addShowRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addShowResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addShowResponse {
        
        public addShowResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findShowById", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findShowByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findShowByIdRequest() {
        }
        
        public findShowByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findShowByIdResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findShowByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.show @return;
        
        public findShowByIdResponse() {
        }
        
        public findShowByIdResponse(EntertainmentNetwork.DAL.ShowService.show @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeShow", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeShowRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.mergeShowRequest arg0;
        
        public mergeShowRequest1() {
        }
        
        public mergeShowRequest1(EntertainmentNetwork.DAL.ShowService.mergeShowRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeShowResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeShowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.show @return;
        
        public mergeShowResponse() {
        }
        
        public mergeShowResponse(EntertainmentNetwork.DAL.ShowService.show @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeShow", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeShowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeShowRequest() {
        }
        
        public removeShowRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeShowResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeShowResponse {
        
        public removeShowResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getShows", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getShowsRequest {
        
        public getShowsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getShowsResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getShowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.show[] @return;
        
        public getShowsResponse() {
        }
        
        public getShowsResponse(EntertainmentNetwork.DAL.ShowService.show[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShowServiceChannel : EntertainmentNetwork.DAL.ShowService.IShowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShowServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.ShowService.IShowService>, EntertainmentNetwork.DAL.ShowService.IShowService {
        
        public ShowServiceClient() {
        }
        
        public ShowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.addShowResponse EntertainmentNetwork.DAL.ShowService.IShowService.addShow(EntertainmentNetwork.DAL.ShowService.addShowRequest1 request) {
            return base.Channel.addShow(request);
        }
        
        public void addShow(EntertainmentNetwork.DAL.ShowService.addShowRequest arg0) {
            EntertainmentNetwork.DAL.ShowService.addShowRequest1 inValue = new EntertainmentNetwork.DAL.ShowService.addShowRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.ShowService.addShowResponse retVal = ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).addShow(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.addShowResponse> EntertainmentNetwork.DAL.ShowService.IShowService.addShowAsync(EntertainmentNetwork.DAL.ShowService.addShowRequest1 request) {
            return base.Channel.addShowAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.addShowResponse> addShowAsync(EntertainmentNetwork.DAL.ShowService.addShowRequest arg0) {
            EntertainmentNetwork.DAL.ShowService.addShowRequest1 inValue = new EntertainmentNetwork.DAL.ShowService.addShowRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).addShowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.findShowByIdResponse EntertainmentNetwork.DAL.ShowService.IShowService.findShowById(EntertainmentNetwork.DAL.ShowService.findShowByIdRequest request) {
            return base.Channel.findShowById(request);
        }
        
        public EntertainmentNetwork.DAL.ShowService.show findShowById(decimal arg0) {
            EntertainmentNetwork.DAL.ShowService.findShowByIdRequest inValue = new EntertainmentNetwork.DAL.ShowService.findShowByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.ShowService.findShowByIdResponse retVal = ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).findShowById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.findShowByIdResponse> EntertainmentNetwork.DAL.ShowService.IShowService.findShowByIdAsync(EntertainmentNetwork.DAL.ShowService.findShowByIdRequest request) {
            return base.Channel.findShowByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.findShowByIdResponse> findShowByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.ShowService.findShowByIdRequest inValue = new EntertainmentNetwork.DAL.ShowService.findShowByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).findShowByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.mergeShowResponse EntertainmentNetwork.DAL.ShowService.IShowService.mergeShow(EntertainmentNetwork.DAL.ShowService.mergeShowRequest1 request) {
            return base.Channel.mergeShow(request);
        }
        
        public EntertainmentNetwork.DAL.ShowService.show mergeShow(EntertainmentNetwork.DAL.ShowService.mergeShowRequest arg0) {
            EntertainmentNetwork.DAL.ShowService.mergeShowRequest1 inValue = new EntertainmentNetwork.DAL.ShowService.mergeShowRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.ShowService.mergeShowResponse retVal = ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).mergeShow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.mergeShowResponse> EntertainmentNetwork.DAL.ShowService.IShowService.mergeShowAsync(EntertainmentNetwork.DAL.ShowService.mergeShowRequest1 request) {
            return base.Channel.mergeShowAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.mergeShowResponse> mergeShowAsync(EntertainmentNetwork.DAL.ShowService.mergeShowRequest arg0) {
            EntertainmentNetwork.DAL.ShowService.mergeShowRequest1 inValue = new EntertainmentNetwork.DAL.ShowService.mergeShowRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).mergeShowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.removeShowResponse EntertainmentNetwork.DAL.ShowService.IShowService.removeShow(EntertainmentNetwork.DAL.ShowService.removeShowRequest request) {
            return base.Channel.removeShow(request);
        }
        
        public void removeShow(decimal arg0) {
            EntertainmentNetwork.DAL.ShowService.removeShowRequest inValue = new EntertainmentNetwork.DAL.ShowService.removeShowRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.ShowService.removeShowResponse retVal = ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).removeShow(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.removeShowResponse> EntertainmentNetwork.DAL.ShowService.IShowService.removeShowAsync(EntertainmentNetwork.DAL.ShowService.removeShowRequest request) {
            return base.Channel.removeShowAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.removeShowResponse> removeShowAsync(decimal arg0) {
            EntertainmentNetwork.DAL.ShowService.removeShowRequest inValue = new EntertainmentNetwork.DAL.ShowService.removeShowRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).removeShowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.getShowsResponse EntertainmentNetwork.DAL.ShowService.IShowService.getShows(EntertainmentNetwork.DAL.ShowService.getShowsRequest request) {
            return base.Channel.getShows(request);
        }
        
        public EntertainmentNetwork.DAL.ShowService.show[] getShows() {
            EntertainmentNetwork.DAL.ShowService.getShowsRequest inValue = new EntertainmentNetwork.DAL.ShowService.getShowsRequest();
            EntertainmentNetwork.DAL.ShowService.getShowsResponse retVal = ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).getShows(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getShowsResponse> EntertainmentNetwork.DAL.ShowService.IShowService.getShowsAsync(EntertainmentNetwork.DAL.ShowService.getShowsRequest request) {
            return base.Channel.getShowsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getShowsResponse> getShowsAsync() {
            EntertainmentNetwork.DAL.ShowService.getShowsRequest inValue = new EntertainmentNetwork.DAL.ShowService.getShowsRequest();
            return ((EntertainmentNetwork.DAL.ShowService.IShowService)(this)).getShowsAsync(inValue);
        }
    }
}
