/* 
* This module is part of the Entertainment Network system 
* Copyright (c) SCC Soft Computer, Inc. 2018 
* All Rights Reserved 
* 
* This document contains unpublished, confidential and proprietary 
* information of SCC Soft Computer, Inc. No disclosure or use of 
* any portion of the contents of these materials may be made without the 
* express written consent of Soft Computer Consultants, Inc. 
* 
*/ 

package isd.dp.ua.EntertainmentNetworkServer.Models;
// Generated Feb 9, 2018 5:32:55 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import isd.dp.ua.EntertainmentNetworkServer.Common.BaseModel;

/**
 * Sit generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType
@Entity
@Table(name = "SIT", schema = "PBAB", uniqueConstraints = @UniqueConstraint(columnNames = { "SIT_ROW", "SIT_FLOOR", "SIT_NUM" }))
public class Sit extends BaseModel implements java.io.Serializable
{

	private BigDecimal sitId;
	@XmlTransient
	private Hall hall;
	private BigDecimal sitNum;
	private BigDecimal sitRow;
	private BigDecimal sitFloor;
	private BigDecimal sitType;

	public Sit()
	{
	}

	public Sit(BigDecimal sitId, Hall hall, BigDecimal sitNum, BigDecimal sitRow, BigDecimal sitFloor,
			BigDecimal sitType)
	{
		this.sitId = sitId;
		this.hall = hall;
		this.sitNum = sitNum;
		this.sitRow = sitRow;
		this.sitFloor = sitFloor;
		this.sitType = sitType;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SIT_SEQ")
    @SequenceGenerator(name = "SIT_SEQ", sequenceName = "SIT_SEQ")
	@Column(name = "SIT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSitId()
	{
		return this.sitId;
	}

	public void setSitId(BigDecimal sitId)
	{
		this.sitId = sitId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SIT_HAL_ID", nullable = false)
	public Hall getHall()
	{
		return this.hall;
	}

	public void setHall(Hall hall)
	{
		this.hall = hall;
	}
	
	@Transient
	@XmlElement
	public BigDecimal getCinemaId()
	{
		return this.getHall() == null ? new BigDecimal("-1") : this.getHall().getHalId();
	}

	@Column(name = "SIT_NUM", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSitNum()
	{
		return this.sitNum;
	}

	public void setSitNum(BigDecimal sitNum)
	{
		this.sitNum = sitNum;
	}

	@Column(name = "SIT_ROW", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSitRow()
	{
		return this.sitRow;
	}

	public void setSitRow(BigDecimal sitRow)
	{
		this.sitRow = sitRow;
	}

	@Column(name = "SIT_FLOOR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSitFloor()
	{
		return this.sitFloor;
	}

	public void setSitFloor(BigDecimal sitFloor)
	{
		this.sitFloor = sitFloor;
	}

	@Column(name = "SIT_TYPE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSitType()
	{
		return this.sitType;
	}

	public void setSitType(BigDecimal sitType)
	{
		this.sitType = sitType;
	}

	@Override
	public String toString()
	{
		return "Sit [sitId=" + sitId + "]";
	}
}
