//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.CinemaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", ConfigurationName="CinemaService.ICinemaService")]
    public interface ICinemaService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/addCinemaRe" +
            "quest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/addCinemaRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        EntertainmentNetwork.DAL.CinemaService.addCinemaResponse addCinema(EntertainmentNetwork.DAL.CinemaService.addCinemaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/addCinemaRe" +
            "quest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/addCinemaRe" +
            "sponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.addCinemaResponse> addCinemaAsync(EntertainmentNetwork.DAL.CinemaService.addCinemaRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/findCinemaB" +
            "yNameRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/findCinemaB" +
            "yNameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.findCinemaByNameResponse findCinemaByName(EntertainmentNetwork.DAL.CinemaService.findCinemaByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/findCinemaB" +
            "yNameRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/findCinemaB" +
            "yNameResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByNameResponse> findCinemaByNameAsync(EntertainmentNetwork.DAL.CinemaService.findCinemaByNameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/mergeCinema" +
            "Request", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/mergeCinema" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.mergeCinemaResponse mergeCinema(EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/mergeCinema" +
            "Request", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/mergeCinema" +
            "Response")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.mergeCinemaResponse> mergeCinemaAsync(EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest1 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/findCinemaB" +
            "yIdRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/findCinemaB" +
            "yIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse findCinemaById(EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/findCinemaB" +
            "yIdRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/findCinemaB" +
            "yIdResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse> findCinemaByIdAsync(EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/removeCinem" +
            "aRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/removeCinem" +
            "aResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse removeCinema(EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/removeCinem" +
            "aRequest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/removeCinem" +
            "aResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse> removeCinemaAsync(EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/getCinemasR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/getCinemasR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseModel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(baseDto))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.getCinemasResponse getCinemas(EntertainmentNetwork.DAL.CinemaService.getCinemasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/getCinemasR" +
            "equest", ReplyAction="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/ICinemaService/getCinemasR" +
            "esponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getCinemasResponse> getCinemasAsync(EntertainmentNetwork.DAL.CinemaService.getCinemasRequest request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeCinemaRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class addCinemaRequest : baseDto {
        
        private decimal citIdField;
        
        private bool citIdFieldSpecified;
        
        private string cinNameField;
        
        private string cinIconField;
        
        private string cinAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal citId {
            get {
                return this.citIdField;
            }
            set {
                this.citIdField = value;
                this.RaisePropertyChanged("citId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool citIdSpecified {
            get {
                return this.citIdFieldSpecified;
            }
            set {
                this.citIdFieldSpecified = value;
                this.RaisePropertyChanged("citIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cinName {
            get {
                return this.cinNameField;
            }
            set {
                this.cinNameField = value;
                this.RaisePropertyChanged("cinName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cinIcon {
            get {
                return this.cinIconField;
            }
            set {
                this.cinIconField = value;
                this.RaisePropertyChanged("cinIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cinAddress {
            get {
                return this.cinAddressField;
            }
            set {
                this.cinAddressField = value;
                this.RaisePropertyChanged("cinAddress");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(addCinemaRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(mergeCinemaRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(sit))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hall))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cinema))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class sit : baseModel {
        
        private decimal sitIdField;
        
        private bool sitIdFieldSpecified;
        
        private decimal sitNumField;
        
        private bool sitNumFieldSpecified;
        
        private decimal sitRowField;
        
        private bool sitRowFieldSpecified;
        
        private decimal sitFloorField;
        
        private bool sitFloorFieldSpecified;
        
        private decimal sitTypeField;
        
        private bool sitTypeFieldSpecified;
        
        private decimal cinemaIdField;
        
        private bool cinemaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal sitId {
            get {
                return this.sitIdField;
            }
            set {
                this.sitIdField = value;
                this.RaisePropertyChanged("sitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitIdSpecified {
            get {
                return this.sitIdFieldSpecified;
            }
            set {
                this.sitIdFieldSpecified = value;
                this.RaisePropertyChanged("sitIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public decimal sitNum {
            get {
                return this.sitNumField;
            }
            set {
                this.sitNumField = value;
                this.RaisePropertyChanged("sitNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitNumSpecified {
            get {
                return this.sitNumFieldSpecified;
            }
            set {
                this.sitNumFieldSpecified = value;
                this.RaisePropertyChanged("sitNumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal sitRow {
            get {
                return this.sitRowField;
            }
            set {
                this.sitRowField = value;
                this.RaisePropertyChanged("sitRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitRowSpecified {
            get {
                return this.sitRowFieldSpecified;
            }
            set {
                this.sitRowFieldSpecified = value;
                this.RaisePropertyChanged("sitRowSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal sitFloor {
            get {
                return this.sitFloorField;
            }
            set {
                this.sitFloorField = value;
                this.RaisePropertyChanged("sitFloor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitFloorSpecified {
            get {
                return this.sitFloorFieldSpecified;
            }
            set {
                this.sitFloorFieldSpecified = value;
                this.RaisePropertyChanged("sitFloorSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal sitType {
            get {
                return this.sitTypeField;
            }
            set {
                this.sitTypeField = value;
                this.RaisePropertyChanged("sitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sitTypeSpecified {
            get {
                return this.sitTypeFieldSpecified;
            }
            set {
                this.sitTypeFieldSpecified = value;
                this.RaisePropertyChanged("sitTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal cinemaId {
            get {
                return this.cinemaIdField;
            }
            set {
                this.cinemaIdField = value;
                this.RaisePropertyChanged("cinemaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinemaIdSpecified {
            get {
                return this.cinemaIdFieldSpecified;
            }
            set {
                this.cinemaIdFieldSpecified = value;
                this.RaisePropertyChanged("cinemaIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class hall : baseModel {
        
        private decimal halIdField;
        
        private bool halIdFieldSpecified;
        
        private string halNameField;
        
        private decimal halSitscountField;
        
        private bool halSitscountFieldSpecified;
        
        private sit[] sitsField;
        
        private decimal cinemaIdField;
        
        private bool cinemaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal halId {
            get {
                return this.halIdField;
            }
            set {
                this.halIdField = value;
                this.RaisePropertyChanged("halId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halIdSpecified {
            get {
                return this.halIdFieldSpecified;
            }
            set {
                this.halIdFieldSpecified = value;
                this.RaisePropertyChanged("halIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string halName {
            get {
                return this.halNameField;
            }
            set {
                this.halNameField = value;
                this.RaisePropertyChanged("halName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal halSitscount {
            get {
                return this.halSitscountField;
            }
            set {
                this.halSitscountField = value;
                this.RaisePropertyChanged("halSitscount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool halSitscountSpecified {
            get {
                return this.halSitscountFieldSpecified;
            }
            set {
                this.halSitscountFieldSpecified = value;
                this.RaisePropertyChanged("halSitscountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sits", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public sit[] sits {
            get {
                return this.sitsField;
            }
            set {
                this.sitsField = value;
                this.RaisePropertyChanged("sits");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal cinemaId {
            get {
                return this.cinemaIdField;
            }
            set {
                this.cinemaIdField = value;
                this.RaisePropertyChanged("cinemaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinemaIdSpecified {
            get {
                return this.cinemaIdFieldSpecified;
            }
            set {
                this.cinemaIdFieldSpecified = value;
                this.RaisePropertyChanged("cinemaIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class cinema : baseModel {
        
        private decimal cinIdField;
        
        private bool cinIdFieldSpecified;
        
        private string cinNameField;
        
        private string cinIconField;
        
        private string cinAddressField;
        
        private hall[] hallsField;
        
        private decimal cityIdField;
        
        private bool cityIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal cinId {
            get {
                return this.cinIdField;
            }
            set {
                this.cinIdField = value;
                this.RaisePropertyChanged("cinId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinIdSpecified {
            get {
                return this.cinIdFieldSpecified;
            }
            set {
                this.cinIdFieldSpecified = value;
                this.RaisePropertyChanged("cinIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cinName {
            get {
                return this.cinNameField;
            }
            set {
                this.cinNameField = value;
                this.RaisePropertyChanged("cinName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cinIcon {
            get {
                return this.cinIconField;
            }
            set {
                this.cinIconField = value;
                this.RaisePropertyChanged("cinIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string cinAddress {
            get {
                return this.cinAddressField;
            }
            set {
                this.cinAddressField = value;
                this.RaisePropertyChanged("cinAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("halls", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public hall[] halls {
            get {
                return this.hallsField;
            }
            set {
                this.hallsField = value;
                this.RaisePropertyChanged("halls");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal cityId {
            get {
                return this.cityIdField;
            }
            set {
                this.cityIdField = value;
                this.RaisePropertyChanged("cityId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cityIdSpecified {
            get {
                return this.cityIdFieldSpecified;
            }
            set {
                this.cityIdFieldSpecified = value;
                this.RaisePropertyChanged("cityIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/")]
    public partial class mergeCinemaRequest : addCinemaRequest {
        
        private decimal cinIdField;
        
        private bool cinIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal cinId {
            get {
                return this.cinIdField;
            }
            set {
                this.cinIdField = value;
                this.RaisePropertyChanged("cinId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cinIdSpecified {
            get {
                return this.cinIdFieldSpecified;
            }
            set {
                this.cinIdFieldSpecified = value;
                this.RaisePropertyChanged("cinIdSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCinema", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addCinemaRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.addCinemaRequest arg0;
        
        public addCinemaRequest1() {
        }
        
        public addCinemaRequest1(EntertainmentNetwork.DAL.CinemaService.addCinemaRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addCinemaResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class addCinemaResponse {
        
        public addCinemaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCinemaByName", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findCinemaByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public findCinemaByNameRequest() {
        }
        
        public findCinemaByNameRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCinemaByNameResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findCinemaByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.cinema[] @return;
        
        public findCinemaByNameResponse() {
        }
        
        public findCinemaByNameResponse(EntertainmentNetwork.DAL.CinemaService.cinema[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeCinema", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeCinemaRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest arg0;
        
        public mergeCinemaRequest1() {
        }
        
        public mergeCinemaRequest1(EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mergeCinemaResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class mergeCinemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.cinema @return;
        
        public mergeCinemaResponse() {
        }
        
        public mergeCinemaResponse(EntertainmentNetwork.DAL.CinemaService.cinema @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCinemaById", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findCinemaByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findCinemaByIdRequest() {
        }
        
        public findCinemaByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCinemaByIdResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class findCinemaByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.cinema @return;
        
        public findCinemaByIdResponse() {
        }
        
        public findCinemaByIdResponse(EntertainmentNetwork.DAL.CinemaService.cinema @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeCinema", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeCinemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeCinemaRequest() {
        }
        
        public removeCinemaRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeCinemaResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class removeCinemaResponse {
        
        public removeCinemaResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCinemas", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getCinemasRequest {
        
        public getCinemasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCinemasResponse", WrapperNamespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", IsWrapped=true)]
    public partial class getCinemasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interfaces.EntertainmentNetworkServer.ua.dp.isd/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.cinema[] @return;
        
        public getCinemasResponse() {
        }
        
        public getCinemasResponse(EntertainmentNetwork.DAL.CinemaService.cinema[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICinemaServiceChannel : EntertainmentNetwork.DAL.CinemaService.ICinemaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CinemaServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.CinemaService.ICinemaService>, EntertainmentNetwork.DAL.CinemaService.ICinemaService {
        
        public CinemaServiceClient() {
        }
        
        public CinemaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CinemaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinemaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinemaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.addCinemaResponse EntertainmentNetwork.DAL.CinemaService.ICinemaService.addCinema(EntertainmentNetwork.DAL.CinemaService.addCinemaRequest1 request) {
            return base.Channel.addCinema(request);
        }
        
        public void addCinema(EntertainmentNetwork.DAL.CinemaService.addCinemaRequest arg0) {
            EntertainmentNetwork.DAL.CinemaService.addCinemaRequest1 inValue = new EntertainmentNetwork.DAL.CinemaService.addCinemaRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CinemaService.addCinemaResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).addCinema(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.addCinemaResponse> EntertainmentNetwork.DAL.CinemaService.ICinemaService.addCinemaAsync(EntertainmentNetwork.DAL.CinemaService.addCinemaRequest1 request) {
            return base.Channel.addCinemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.addCinemaResponse> addCinemaAsync(EntertainmentNetwork.DAL.CinemaService.addCinemaRequest arg0) {
            EntertainmentNetwork.DAL.CinemaService.addCinemaRequest1 inValue = new EntertainmentNetwork.DAL.CinemaService.addCinemaRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).addCinemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.findCinemaByNameResponse EntertainmentNetwork.DAL.CinemaService.ICinemaService.findCinemaByName(EntertainmentNetwork.DAL.CinemaService.findCinemaByNameRequest request) {
            return base.Channel.findCinemaByName(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.cinema[] findCinemaByName(string arg0) {
            EntertainmentNetwork.DAL.CinemaService.findCinemaByNameRequest inValue = new EntertainmentNetwork.DAL.CinemaService.findCinemaByNameRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CinemaService.findCinemaByNameResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).findCinemaByName(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByNameResponse> EntertainmentNetwork.DAL.CinemaService.ICinemaService.findCinemaByNameAsync(EntertainmentNetwork.DAL.CinemaService.findCinemaByNameRequest request) {
            return base.Channel.findCinemaByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByNameResponse> findCinemaByNameAsync(string arg0) {
            EntertainmentNetwork.DAL.CinemaService.findCinemaByNameRequest inValue = new EntertainmentNetwork.DAL.CinemaService.findCinemaByNameRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).findCinemaByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.mergeCinemaResponse EntertainmentNetwork.DAL.CinemaService.ICinemaService.mergeCinema(EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest1 request) {
            return base.Channel.mergeCinema(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.cinema mergeCinema(EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest arg0) {
            EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest1 inValue = new EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest1();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CinemaService.mergeCinemaResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).mergeCinema(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.mergeCinemaResponse> EntertainmentNetwork.DAL.CinemaService.ICinemaService.mergeCinemaAsync(EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest1 request) {
            return base.Channel.mergeCinemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.mergeCinemaResponse> mergeCinemaAsync(EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest arg0) {
            EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest1 inValue = new EntertainmentNetwork.DAL.CinemaService.mergeCinemaRequest1();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).mergeCinemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse EntertainmentNetwork.DAL.CinemaService.ICinemaService.findCinemaById(EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest request) {
            return base.Channel.findCinemaById(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.cinema findCinemaById(decimal arg0) {
            EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest inValue = new EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).findCinemaById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse> EntertainmentNetwork.DAL.CinemaService.ICinemaService.findCinemaByIdAsync(EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest request) {
            return base.Channel.findCinemaByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse> findCinemaByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest inValue = new EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).findCinemaByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse EntertainmentNetwork.DAL.CinemaService.ICinemaService.removeCinema(EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest request) {
            return base.Channel.removeCinema(request);
        }
        
        public void removeCinema(decimal arg0) {
            EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest inValue = new EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).removeCinema(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse> EntertainmentNetwork.DAL.CinemaService.ICinemaService.removeCinemaAsync(EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest request) {
            return base.Channel.removeCinemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse> removeCinemaAsync(decimal arg0) {
            EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest inValue = new EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).removeCinemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.getCinemasResponse EntertainmentNetwork.DAL.CinemaService.ICinemaService.getCinemas(EntertainmentNetwork.DAL.CinemaService.getCinemasRequest request) {
            return base.Channel.getCinemas(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.cinema[] getCinemas() {
            EntertainmentNetwork.DAL.CinemaService.getCinemasRequest inValue = new EntertainmentNetwork.DAL.CinemaService.getCinemasRequest();
            EntertainmentNetwork.DAL.CinemaService.getCinemasResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).getCinemas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getCinemasResponse> EntertainmentNetwork.DAL.CinemaService.ICinemaService.getCinemasAsync(EntertainmentNetwork.DAL.CinemaService.getCinemasRequest request) {
            return base.Channel.getCinemasAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getCinemasResponse> getCinemasAsync() {
            EntertainmentNetwork.DAL.CinemaService.getCinemasRequest inValue = new EntertainmentNetwork.DAL.CinemaService.getCinemasRequest();
            return ((EntertainmentNetwork.DAL.CinemaService.ICinemaService)(this)).getCinemasAsync(inValue);
        }
    }
}
